<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getStoreId();
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php 
// if($_SERVER['REQUEST_URI'] == 'catalogsearch/'){ 
$uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
if (($uri_parts[0] == '/catalogsearch/result/') || ($uri_parts[0] == '/catalogsearch/result/index/') ) {
    $searchc = 1;
} else {
    $searchc = 0;
}
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
        <?php $jj = 1; ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <?php  // custom category path 
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $categories =  $_product->getCategoryIds(); /*will return category ids array*/
                foreach($categories as $category){     
                 $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                $cid = $cat->getId();
                    if(($cid != 27) && ($cid != 2) && ($cid != 22) && ($cid != 23)) {
                         $catl = $cat->getUrl();
                         $newm =1;
                    }
                 } 
                $newurl = $catl."/". $_product->getUrlKey();           
                //   custom  category path 
            ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <!-- custom place -->
                    <div class="product-item-inner custom <?php echo $viewMode; ?>">
                            <div class="product actions product-item-actions custom"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>  
                        </div>
                        <!-- custom place -->
                    <?php if ($searchc == 1) { ?>
                            <a href="<?php echo  $newurl;?>"
                            class="product photo product-item-photo 1"
                            tabindex="-1" >
                                <?= $productImage->toHtml() ?>
                            </a>
                    <?php }  elseif($newm == 1) { ?>
                     <a href="<?php echo  $newurl;?>"
                        class="product photo product-item-photo 3"
                        tabindex="-1" >
                            <?= $productImage->toHtml() ?>
                        </a>
                    <?php }  else { ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo 2"
                        tabindex="-1" >
                            <?= $productImage->toHtml() ?>
                        </a>
                    <?php } ?>
                    <!-- custom place -->
                     <!-- add to cart -->
                     <div class="product actions customs product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <!-- add to cart -->
                               <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if($_product->getTypeId() == 'simple'){ ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                            <?php } else { ?>
                                             <a href="<?php echo  $newurl;?>" class="action tocart primary">
                                               <span> Add to Cart </span>
                                            </a>
                                            <?php } ?>
                                        </form>
                                    <?php else :?>
                                        <?php if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <!-- add to cart -->                             
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                        <?php if ($searchc == 1) { ?>
                            <a class="product-item-link" 
                               href="<?php echo  $newurl;?>">
                        <?php }  elseif($newm == 1) { ?>
                        <a class="product-item-link" 
                               href="<?php echo  $newurl;?>">
                        <?php } else { ?>
                            <a class="product-item-link" 
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                        <?php } ?>
                                <?php /* @noEscape */ $name = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                    <?php if ($viewMode == 'grid') { ?>
                                        <?php echo $name = strlen($name ) > 50 ? substr($name ,0,43)."..." : $name ;?>
                                    <?php } else {
                                         echo $name;
                                     } ?>
                                <?php } else {
                                  echo $name;
                                } ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                         <!-- custom code for configure -->
                         <?php $ptype = $_product->getTypeId();?>
                                    <?php  if($ptype=='configurable'): ?>
                                        <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                        <?php $product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_product->getId()); ?>
                                        <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                        $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product); ?>
                                         <!-- new code -->
                                         <?php 
                                         $_children = $product->getTypeInstance()->getUsedProducts($product);
                                         $attributeValue1=[];
                                         $attributeValue2=[];
                                         $attributeValue3=[];
                                         $cweight_array=[];
                                        foreach ($_children as $child){ 
                                            $cweight1 = $child->getWeight();
                                            array_push($cweight_array,$cweight1);
                                            $attribute1 = $child->getResource()->getAttribute('grams');
                                            $attribute2 = $child->getResource()->getAttribute('kg');
                                            $attribute3 = $child->getResource()->getAttribute('litre');
                                        // Get Value
                                        array_push($attributeValue1,$attribute1->getFrontend()->getValue($child)); 
                                        array_push($attributeValue2,$attribute2->getFrontend()->getValue($child)); 
                                        array_push($attributeValue3,$attribute3->getFrontend()->getValue($child)); 
                                        // Get Label
                                        $attributeLabel1 = $attribute1->getStoreLabel(); 
                                        $attributeLabel2 = $attribute2->getStoreLabel();
                                         $attributeLabel3 = $attribute3->getStoreLabel(); ?>
                                       <?php }?>
                                       <p style="display:none;"><?php
                                       asort($cweight_array);
                                       $new_weight=array();
                                       foreach($cweight_array as $x => $x_value) {
                                        array_push($new_weight,$x_value);
                                      }
                                       
                                        ?> </p>
                                         <span class="custom-kg widget">
                                        <?php 
                                        if(isset($new_weight) && count($new_weight)>0){
                                            $cc = $new_weight[0];
                                            if ($cc == 0.10000) {
                                                $cc = 100;
                                            }
                                            if ($cc == 0.50000) {
                                                $cc = 0.5;
                                            }
                                            if ($cc == 0.25000) {
                                                $cc = 0.25;
                                            }
                                            if ($cc == 0.02500) {
                                                $cc = 0.025;
                                            }
                                            if ($cc == 0.01000) {
                                                $cc = 0.01;
                                            }
                                            if ($cc == 0.03000) {
                                                $cc = 0.03;
                                            }
                                            if ($cc == 0.3000) {
                                                $cc = 0.3;
                                            }
                                            if(isset($attributeValue1) && count($attributeValue1)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue1[0]);
                                                if($result!='')
                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                                
                                            }  
                                            if(isset($attributeValue2) && count($attributeValue2)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue2[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                            if(isset($attributeValue3) && count($attributeValue3)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue3[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                        } ?>
                                        </span>
                                        <!-- new code -->
                                <?php endif ?>
                                <!-- custom code for configure -->
                                 <!-- sale countdown -->
                                 <?php if($_product->getTypeId() == 'simple'){ 
                                            $date = date_default_timezone_set('Asia/Kolkata');
                                            $currentDate =  date('d-m-Y');
                                            $todate      =  $_product->getSpecialToDate();
                                            $fromdate    =  $_product->getSpecialFromDate(); 
                                            $newcurrent  =  date('Y-m-d');                                        
                                            // 2021/08/12 00:00:00
                                            if($_product->getSpecialPrice() != 0 || $_product->getSpecialPrice()) {
                                                if($_product->getSpecialToDate() != null) {
                                                    if(strtotime($todate) >= strtotime($currentDate) && strtotime($fromdate) <= strtotime($currentDate)){ 
                                                        if(strtotime($todate) == strtotime($currentDate)) {
                                                            $newtodate = $newcurrent . "T24:00:00";
                                                            $newtodate  =  str_replace(' ','',$newtodate);
                                                        }
                                                        else { 
                                                            $newtodate = str_replace('/','-',$_product->getSpecialToDate());
                                                            $newtodate  =  str_replace('00:00:00','T24:00:00',$newtodate);
                                                            $newtodate  =  str_replace(' ','',$newtodate);
                                                        }?>
                                                        <div id="countdowntimer" class="countdowntimer"><p style="color: #e66b6b;">Hurry up! sale end soon</p><span id="catalog_date<?php echo $jj; ?>" class="catalog_date"><span></div>
                                                        <script>
                                                             require(['jquery','js/countdown'], function ($) {
                                                                    console.log('countdowntimer start');
                                                                    var var1 = "<?php echo $jj; ?>";
                                                                    $('#catalog_date'+var1).countdowntimer({
                                                                        startDate : "<?php echo date('Y/m/d H:i:s'); ?>",
                                                                        dateAndTime : "<?php echo $newtodate;?>",
                                                                        size : "lg",
                                                                        regexpMatchFormat: "([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})",
                                                            // 			regexpReplaceWith: "$1 days $2 hours $3 minutes $4 seconds REMAINING"        
                                                                        regexpReplaceWith: "<div><span>$1</span><span>days</span></div> <div><span>$2</span><span>hours</span></div> <div><span>$3</span><span>mins</span></div> <div><span>$4</span><span>secs</span></div>"
                                                                    });  
                                                            });
                                                        </script>
                                                        <?php $jj++;
                                                     }   
                                                }
                                            } 
                                        }?>
                                        <!-- sale countdown -->
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                         

                        <div class="product-item-inner">
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <?php if ($searchc == 1) { ?>
                                        <a href="<?php echo $newurl; ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more1"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php }  elseif($newm == 1) { ?>
                                     <a href="<?php echo $newurl; ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more1"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php } else { ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php } ?>
                                </div>

                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

