<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>

<?php $wcount = $customerSession->getWishlistItemCount(); ?>




<div data-block="minicart" class="minicart-wrapper" id="custom-cart">
<!-- <a href="quick-orders" class="q-order" >Quick Order</a> -->
<a href="https://api.whatsapp.com/send?phone=+919361008194" class="wtp" target="_blank">
    <img class="lazy loaded whatsapp mplazyload" data-src="<?php echo $baseUrl;?>pub/media/home/whatsapp.png">
    <div class="ss-wtp">
        <p>Support</p>
         <div class="wtp-no">+91 93610 08194</div>
     </div>
</a>

    <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="wh-top" href="<?php echo $this->getUrl('wishlist') ?>" data-bind="scope: 'wishlist'">
    <i class="fa fa-heart-o" aria-hidden="true"></i>
        <span class="text"><?= $block->escapeHtml($block->getLabel()) ?></span>
        <!-- ko if: wishlist().counter -->
        <span class="counter qty wishcount"><?php echo $wcount; ?></span>
        <!-- /ko -->
         <!-- ko ifnot: wishlist().counter -->
         <span class="counter qty wishcount">0</span>
        <!-- /ko -->
    </a>
    <a class="action showcart" href="<?= $block->escapeUrl($block->getShoppingCartUrl()) ?>"
       data-bind="scope: 'minicart_content'">
       <!-- <i class="fa fa-shopping-cart" aria-hidden="true"></i> -->
       <img class="custom-user mplazyload" data-src="<?php echo $baseUrl; ?>pub/media/home/shopping-bag.png">
       <img class="custom-user mobile mplazyload" style="display:none;" data-src="<?php echo $baseUrl; ?>pub/media/home/shopping-bag-mob.png">
        <span class="text"><?= $block->escapeHtml(__('My Cart')) ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false && !isLoading() }, blockLoader: isLoading">
              
            <!-- customcode -->
             
             <span class="counter-number" >
                 <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
            </span>
           
            <!-- ko ifnot: getCartParam('summary_count') -->
                <span class="counter-number zero">0</span>
            <!-- /ko -->
            <!-- custom code -->


            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) :?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else :?>
        <script>
            require(['jquery'], function ($) {
                $('a.action.showcart').click(function() {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @noEscape */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= $block->escapeJs(
                $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))
            ) ?>"
        }
    }
    </script>
</div>


