<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$storeid = $storeManager->getStore()->getStoreId();
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php 
// if($_SERVER['REQUEST_URI'] == 'catalogsearch/'){ 
$uri_parts = explode('?', $_SERVER['REQUEST_URI'], 2);
if (($uri_parts[0] == '/catalogsearch/result/') || ($uri_parts[0] == '/catalogsearch/result/index/') ) {
    $searchc = 1;
} else {
    $searchc = 0;
}
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
            <?php $jj = 1; ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <?php  // custom category path 
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $categories =  $_product->getCategoryIds(); /*will return category ids array*/
                foreach($categories as $category){     
                 $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                $cid = $cat->getId();
                    if(($cid != 27) && ($cid != 2) && ($cid != 22) && ($cid != 23)) {
                         $catl = $cat->getUrl();
                         $newm =1;
                    }
                 } 
                $newurl = $catl."/". $_product->getUrlKey();           
                //   custom  category path 
            ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <!-- custom place -->
                    <div class="product-item-inner custom <?php echo $viewMode; ?>">
                            <div class="product actions product-item-actions custom"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>  
                        </div>
                        <!-- custom place -->
                    <?php if ($searchc == 1) { ?>
                            <a href="<?php echo  $newurl;?>"
                            class="product photo product-item-photo 1"
                            tabindex="-1" >
                                <?= $productImage->toHtml() ?>
                            </a>
                    <?php }  elseif($newm == 1) { ?>
                     <a href="<?php echo  $newurl;?>"
                        class="product photo product-item-photo 3"
                        tabindex="-1" >
                            <?= $productImage->toHtml() ?>
                        </a>
                    <?php }  else { ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo 2"
                        tabindex="-1" >
                            <?= $productImage->toHtml() ?>
                        </a>
                    <?php } ?>
                    <!-- custom place -->
                     <!-- add to cart -->
                     <div class="product actions customs product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <!-- add to cart -->
                               <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if($_product->getTypeId() == 'simple'){ ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary cc">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                             <!-- custom popup  -->
                                             <?php $ccsku = $_product->getSku(); ?>
                                               <div class="popup-cart-custom popup-cart-custom-<?php echo $ccsku; ?>" style="display: none;">
                                               <p class="popup-success"> You added <span><?php echo $_product->getName();?> </span>to your shopping cart.</p>
                                                <div class="pop-related-btn">
                                                    <a class="action" href="<?php if($storeid == 2) {echo $baseUrl."ta/";}else {echo $baseUrl;} ?>checkout/cart">View Cart</a>
                                                    <button class="action" type="button" data-role="action"><span>Continue Shopping</span></button>
                                                </div>
                                                    <?php 
                                                    $product1 = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                                    $relatedProducts = $product1->getRelatedProducts();
                                                    if (!empty($relatedProducts)) { ?>
                                                            <h3> You might also like </h3>
                                                            <div class="rel-pro">
                                                        <?php 
                                                        $ii = 1;
                                                        foreach ($relatedProducts as $relatedProduct) {
                                                            if ($ii <= 3) {
                                                                $_product1 = $objectManager->create('Magento\Catalog\Model\Product')->load($relatedProduct->getId()); ?>
                                                             <?php if($_product1->getVisibility() == 4) { ?>
                                                                <div class="related-img">
                                                                <a class="you-might-also-like" href="<?php echo $_product1->getProductUrl();?>" target="_blank"><img src="<?php echo $baseUrl;?>pub/media/catalog/product/<?php echo $_product1->getData('small_image');?>"></a>   
                                                                <?php $name= $_product1->getName();?>                
                                                                <p class="related-name">
                                                                    <a class="you-might-also-like" href="<?php echo $_product1->getProductUrl();?>" target="_blank">
                                                                    <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                                                            <?php echo $name = strlen($name ) > 50 ? substr($name ,0,30)."..." : $name ;?>
                                                                        <?php } else {
                                                                            echo $name;
                                                                        } ?> 
                                                                   </a></p>
                                                                </div>
                                                            <?php 
                                                             }
                                                            }
                                                            $ii++;
                                                            } ?>
                                                            </div>
                                                        <?php }  ?>
                                                </div>
                                                <!-- custom popup  -->
                                            <?php } elseif (($_product->getTypeId() != 'configurable') && ($_product->getTypeId() != 'simple')){ ?>
                                             <a href="<?php echo  $newurl;?>" class="action tocart primary nn">
                                               <span> Add to Cart </span>
                                            </a>
                                            <?php } ?>
                                        </form>
                                        <!-- quick add -->
                                        <?php   if ($_product->getTypeId() == 'configurable') {
                                                    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
                                                    $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
                                                    $currencySymbol = $currency->getCurrencySymbol(); 
                                                        if ($_product->isAvailable()) {?>
                                                            <figcaption class="card-figcaption <?php echo $viewMode; ?>">
                                                                <div class="card-figcaption-bottom">
                                                                    <a href="javascript:void(0)" data-event-type="product-click" class="button button--small button-quickShop quickadd-<?php echo $_product->getId(); ?>" id="<?php echo $_product->getId(); ?>"><span>ADD TO CART </span></a>
                                                                </div>
                                                                <div class="quickShopPopup scrollbar"></div>
                                                            </figcaption>
                                                    <?php }
                                                } ?>
                                                <!-- quick add -->
                                    <?php else :?>
                                        <?php if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <!-- add to cart -->                             
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                        <?php if ($searchc == 1) { ?>
                            <a class="product-item-link" 
                               href="<?php echo  $newurl;?>">
                        <?php }  elseif($newm == 1) { ?>
                        <a class="product-item-link" 
                               href="<?php echo  $newurl;?>">
                        <?php } else { ?>
                            <a class="product-item-link" 
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                        <?php } ?>
                                <?php /* @noEscape */ $name = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                    <?php if ($viewMode == 'grid') { ?>
                                        <?php echo $name = strlen($name ) > 50 ? substr($name ,0,43)."..." : $name ;?>
                                    <?php } else {
                                         echo $name;
                                     } ?>
                                <?php } else {
                                  echo $name;
                                } ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                         <!-- custom code for configure -->
                         <?php $ptype = $_product->getTypeId();?>
                                    <?php  if($ptype=='configurable'): ?>
                                        <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                        <?php $product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_product->getId()); ?>
                                        <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                        $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product); 
                                        ?>
                                         <!-- new code -->
                                         <?php 
                                         $_children = $product->getTypeInstance()->getUsedProducts($product);
                                         $attributeValue1=[];
                                         $attributeValue2=[];
                                         $attributeValue3=[];
                                         $cweight_array=[];
                                        foreach ($_children as $child){ 
                                            $cweight1 = $child->getWeight();
                                            array_push($cweight_array,$cweight1);
                                            $attribute1 = $child->getResource()->getAttribute('grams');
                                            $attribute2 = $child->getResource()->getAttribute('kg');
                                            $attribute3 = $child->getResource()->getAttribute('litre');
                                        // Get Value
                                        array_push($attributeValue1,$attribute1->getFrontend()->getValue($child)); 
                                        array_push($attributeValue2,$attribute2->getFrontend()->getValue($child)); 
                                        array_push($attributeValue3,$attribute3->getFrontend()->getValue($child)); 
                                        // Get Label
                                        $attributeLabel1 = $attribute1->getStoreLabel(); 
                                        $attributeLabel2 = $attribute2->getStoreLabel();
                                         $attributeLabel3 = $attribute3->getStoreLabel(); ?>
                                       <?php }?>
                                       <p style="display:none;"><?php
                                       asort($cweight_array);
                                       $new_weight=array();
                                       foreach($cweight_array as $x => $x_value) {
                                        array_push($new_weight,$x_value);
                                      }
                                       
                                        ?> </p>
                                         <span class="custom-kg widget">
                                        <?php 
                                        if(isset($new_weight) && count($new_weight)>0){
                                            $cc = $new_weight[0];
                                            if ($cc == 0.10000) {
                                                $cc = 100;
                                            }
                                            if ($cc == 0.50000) {
                                                $cc = 0.5;
                                            }
                                            if ($cc == 0.050000) {
                                                $cc = 50;
                                            }
                                            if ($cc == 0.25000) {
                                                $cc = 0.25;
                                            }
                                            if ($cc == 0.02500) {
                                                $cc = 0.025;
                                            }
                                            if ($cc == 0.01000) {
                                                $cc = 0.01;
                                            }
                                            if ($cc == 0.03000) {
                                                $cc = 0.03;
                                            }
                                            if ($cc == 0.3000) {
                                                $cc = 0.3;
                                            }
                                            if(isset($attributeValue1) && count($attributeValue1)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue1[0]);
                                                if($result!='')
                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                                
                                            }  
                                            if(isset($attributeValue2) && count($attributeValue2)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue2[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                            if(isset($attributeValue3) && count($attributeValue3)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue3[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                        } ?>
                                        </span>
                                        <!-- new code -->
                                <?php endif ?>
                                <!-- custom code for configure -->
                        
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>
                         

                        <div class="product-item-inner">
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <?php if ($searchc == 1) { ?>
                                        <a href="<?php echo $newurl; ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more1"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php }  elseif($newm == 1) { ?>
                                     <a href="<?php echo $newurl; ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more1"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php } else { ?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    <?php } ?>
                                </div>

                            <?php endif; ?>
                            
                        </div>
                    </div>
                </div>
                
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
require(["jquery"],function($){
    // show variant
 jQuery('a.button-quickShop').click(function(){
        var elmId = jQuery(this).attr("id");
        $ = jQuery;
        $('.quickShopPopup.scrollbar.is-open').removeClass('is-open');
        $('.product-item-details').removeClass("is-open");
        $('.quickShopPopup.scrollbar .halo-quickShop').remove();
        $('.card-figcaption.is-open').removeClass('is-open');
        $(this).children("span").css("display", "none");
        $(this).append('<i class="fa fa-circle-o-notch fa-spin"></i>');
        var baseurl = "<?php echo $baseUrl; ?>";
        var pr_id= elmId;
         $.ajax({
            type: 'POST',
            url: baseurl+'helloworld/index/product',
            dataType: 'json',
            showLoader: false,
            cache: false,
            data: { 'pr_id' : pr_id},
            success : function(result){
                $("a.quickadd-"+elmId).children("span").css("display", "inline");
                $("a.quickadd-"+elmId).children("i").remove();
                $("a.quickadd-"+elmId).parent().parent().parent().parent('.product-item-actions').toggleClass("is-open");
                $("a.quickadd-"+elmId).parent().parent().parent().parent('.product-item-actions').next('.product-item-details').addClass("is-open");
            var status = result.status;
            var option = result.option;
            var childid = result.childid;
            var cprice = result.cprice;
            var symb = "<?php echo $currencySymbol ?>"; 
            var attr = result.attr;
                if(status == '1')
                {  
                    $("a.quickadd-"+elmId).parent().next().addClass('is-open');
                    $("a.quickadd-"+elmId).parent().parent('.card-figcaption').addClass('is-open');
                    var quickview_data='<div class="halo-quickShop"><div class="form-field selected"><label class="form-label form-label--inlineSmall" id="rectangle-group-label"><span>'+option[0]+'</span>'+attr+'<small> : '+symb+cprice[0]+'</small></label>';
                    for(var ss=0;ss < option.length;ss++){
                        if(ss == 0) {
                            var dem = '<div class="form-option-wrapper"> <input class="form-radio" checked type="radio" id="attribute_rectangle__'+childid[ss]+'" name="'+cprice[ss]+'" value="'+childid[ss]+'"> <label class="form-option"><span class="form-option-variant">'+option[ss]+'</span></label></div>';
                            quickview_data += dem;
                        } else {
                            var dem = '<div class="form-option-wrapper"> <input class="form-radio" type="radio" id="attribute_rectangle__'+childid[ss]+'" name="'+cprice[ss]+'" value="'+childid[ss]+'"> <label class="form-option"><span class="form-option-variant">'+option[ss]+'</span></label></div>';
                            quickview_data += dem;
                        }
                        
                    }
                    quickview_data +='</div><div class="action-quick-btn"><div id="add-to-cart-wrapper-quick"><div class="form-action"><a href="javascript:void(0)" id="form-action-addToCart" class="button button--tertiary" role="button">SUMBIT</a></div></div><div class="halo-quickShop-action"><a href="javascript:void(0)" class="button halo-quickShop-close" aria-label="'+elmId+'" role="button"> <span>CANCEL</span></a></div></div></div>';
                    $("a.quickadd-"+elmId).parent().next().html(quickview_data);
                }
                else{
                    $("a.quickadd-"+elmId).parent().next().removeClass('is-open');
                }
            }
        });
    });
    // close variant
    $( "body" ).delegate( "a.halo-quickShop-close", "click", function() {
           var clsid = jQuery(this).attr("aria-label");
            $("a.quickadd-"+clsid).parent().next().find('.halo-quickShop').remove();
            $("a.quickadd-"+clsid).parent().parent('.card-figcaption').removeClass('is-open');
            $("a.quickadd-"+clsid).parent().parent().parent().parent('.product-item-actions').removeClass("is-open");
            $("a.quickadd-"+clsid).parent().parent().parent().parent('.product-item-actions').next('.product-item-details').removeClass("is-open");
    });
     // change variant
    $( "body" ).delegate( "label.form-option", "click", function() {
        $('.halo-quickShop input.form-radio').prop( "checked", false );
        $(this).prev('input.form-radio').prop( "checked", true );
        var cprice = $(this).prev('input.form-radio').attr("name");
        var variant = $(this).children('span').text();
        $(this).parents('.form-option-wrapper').parent('.form-field').addClass("selected");
        var symb = "<?php echo $currencySymbol ?>"; 
            $('.form-field.selected').children('label').find('span').text(variant);
            $('.form-field.selected').children('label').find('small').text(' : '+symb+cprice);
    });
    //add variant product
    $( "body" ).delegate( "#form-action-addToCart", "click", function() {
        if ($(".quickShopPopup.is-open .form-radio").is(":checked")) {
        var radioValue = $(this).parents('.action-quick-btn').parent('.halo-quickShop').children(".form-field").find(".form-radio:checked").val();
        $(this).text("Adding..");
        $(this).css("cursor","not-allowed");
        var baseurl = "<?php echo $baseUrl; ?>";
        var prd_id= radioValue;
        $.ajax({
            type: 'POST',
            url: baseurl+'helloworld/index/index',
            dataType: 'json',
            showLoader: false,
            cache: false,
            data: { 'pr_id' : prd_id, 'qty' : 1},
            success : function(result){
             $('#form-action-addToCart').text("SUBMIT");
             $('#form-action-addToCart').css("cursor","grab");
             $('.quickShopPopup.scrollbar.is-open .halo-quickShop').remove();
             $('.card-figcaption.is-open').removeClass('is-open');
             $('.product-item-info .product-item-actions').toggleClass("is-open");
            var status = result.status;
            var pname = result.pname;
                if(status == '1')
                {
                    require(['jquery','Magento_Customer/js/customer-data'], function ($,customerData) { 
                    var sections = ['cart'];
                        customerData.invalidate(sections);
                        customerData.reload(sections, true);
                    });
                    $(window).scrollTop(20);
                    $(".page.messages").html('<div class="message-success success message" data-ui-id="message-success"><div data-bind="html: message.text">You added '+pname+' to your <a href="'+baseurl+'"checkout/cart/">shopping cart</a>.</div></div>');
                    setTimeout(function(){
                    $('.message-success.success.message').remove();
                    }, 3000);
                    $('.product-item-details').removeClass("is-open");
                    $('.product-item-actions').removeClass("is-open");
                    
                }
                else{
                    $(window).scrollTop(20);
                    $(".page.messages").html('<div class="message-error error message" data-ui-id="message-success"><div data-bind="html: message.text"> Something Went wrong.Please try agian later.</div></div>');
                    setTimeout(function(){
                    $('.message-error.error.message').remove();
                    }, 3000);
                }
            }
        });
        } else{
            $(this).parents('.form-action').append('<div class="ui-tooltip ui-widget ui-corner-all ui-widget-content"><div class="ui-tooltip-content">Please select one this option</div></div>');
                setTimeout(function(){
                    $('.action-quick-btn .ui-tooltip').remove();
                }, 3000);
            }  
    });
});
</script>
<style>
.form-action .ui-tooltip{
    display: block;
    border: 1px solid #ededed;
    padding: 10px;
    position: absolute;
    z-index: 9999;
    bottom: 45px;
    width: max-content;
    left: 0px;
}
.card-figcaption.list  {
    display: inline-block;
}
.card-figcaption.list .halo-quickShop{box-shadow: 2px 2px 4px #a9a;padding:30px 3px;}
</style>
