<div class="halo-quickShop">
    <div class="halo-quickShop-content">
        <div class="productView-details product-options">
            <div class="productView-options halo-productOptions">
                <form class="form" method="post" action="https://www.physiqapparel.com/cart.php" enctype="multipart/form-data" data-cart-item-add>
                    <input type="hidden" name="action" value="add">
                    <input type="hidden" name="product_id" value="1737"/>
                    <div data-product-option-change>
                            <div class="form-field" data-product-attribute="set-rectangle" data-product-option-id="2379" role="radiogroup" aria-labelledby="rectangle-group-label">
                                <label class="form-label form-label--alternate form-label--inlineSmall" id="rectangle-group-label">
                                    Size:<small>(Required)</small>
                                </label>
                                <div class="form-option-wrapper">    
                                    <input
                                        class="form-radio"
                                        type="radio"
                                        id="attribute_rectangle__2379_151"
                                        name="attribute[2379]"
                                        value="151"
                                        required
                                        data-title="XS"
                                        data-index="0"
                                    >
                                    <label class="form-option" for="attribute_rectangle__2379_151" data-product-attribute-value="151">
                                            <span class="form-option-variant">XS</span>
                                    </label>
                                </div>
                            </div>

                    </div>
                    <div id="add-to-cart-wrapper" >
        <div class="form-field form-field--increments">
            <label class="form-label form-label--alternate"
                   for="qty[]">Quantity:</label>
                <div class="form-increment" data-quantity-change>
                    <button class="button button--icon" data-action="dec">
                        <span class="is-srOnly">Decrease Quantity of undefined</span>
                    </button>
                    <input class="form-input form-input--incrementTotal"
                           id="qty[]"
                           name="qty[]"
                           type="tel"
                           value="1"
                           data-quantity-min="0"
                           data-quantity-max="0"
                           min="1"
                           pattern="[0-9]*"
                           aria-live="polite">
                    <button class="button button--icon" data-action="inc">
                        <span class="is-srOnly">Increase Quantity of undefined</span>
                    </button>
                </div>
        </div>

    <div class="alertBox productAttributes-message" style="display:none">
        <div class="alertBox-column alertBox-icon">
            <icon glyph="ic-success" class="icon" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"></path></svg></icon>
        </div>
        <p class="alertBox-column alertBox-message"></p>
    </div>
        <div class="form-action">
            <input
                    id="form-action-addToCart"
                    data-wait-message="Adding to cart…"
                    class="button button--tertiary"
                    type="submit"
                    value="Submit"
            >
            <span class="product-status-message aria-description--hidden">Adding to cart… The item has been added</span>
        </div>
</div>
                    <div class="halo-quickShop-action">
                        <a href="javascript:void(0)" class="button halo-quickShop-close" aria-label="Close" role="button">
                            <span>Cancel</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
