<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getStoreId();
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $tittle=$block->getTitle(); 
    
    $items = $block->getProductCollection()->getItems();
    // $items =  $items->addAttributeToSort('position','ASC');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
<div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
    <div class="block-content">
         <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                 <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <table class="table-quick-order">
                        <tr class="header-quick-order">
                            <th>Product Name</th>
                            <th>Weight</th>
                            <th style="text-align:center;">quantity</th>
                            <th>Total Price</th>
                            <th> </th>
                        </tr>

                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item) : ?>
                                <?php if($_item->getIsSalable()) { ?>
                                <tr class="body-quick-order">
                                <td>
                                    <div class="product-item-quick">
                                        <!-- custom category path -->
                                        <?php $categories = $_item->getCategoryIds(); /*will return category ids array*/
                                            $j = 0;
                                            foreach($categories as $key => $category){     
                                                $j++;
                                                $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                                $j++;
                                                $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                                $cid = $cat->getId();
                                                    if(($cid != 27) && ($cid != 2) && ($cid != 22) && ($cid != 23)) {
                                                        $catl = $cat->getUrl();
                                                    }
                                            } 
                                            $newurl1 = $catl."/".$_item->getUrlKey(); 
                                        ?> 
                                        <!-- custom  category path -->
                                        <div class="product-item-photo-quick">
                                        <a href="<?= $newurl1; ?>" class="product-item-photo">
                                            <?= $block->getImage($_item, $image)->toHtml() ?>
                                        </a>
                                        </div>
                                        <div class="product-item-details">
                                            <strong class="product-item-name">
                                                <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                                href="<?= $newurl1; ?>"
                                                class="product-item-link" >
                                                <?php $name= $block->escapeHtml($_item->getName()) ?>
                                                <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                            <?php echo $name = strlen($name ) > 50 ? substr($name ,0,43)."..." : $name ;?>
                                            <?php } else {
                                            echo $name;
                                            } ?>
                                                </a>
                                            </strong>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                <?php $ptype = $_item->getTypeId();?>
                                <?php  if($ptype=='configurable') { ?>
                                    <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                    <?php //$product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_item->getId()); ?>
                                    <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable'); ?>
                                    <!-- new code -->
                                    <?php 
                                         $_children = $_item->getTypeInstance()->getUsedProducts($_item); ?>
                                         <select name="weightoption" id="weightoption">

                                        <?php  foreach ($_children as $child){ 
                                              if($child->getIsSalable()) { ?>

                                            <?php if(isset($child['kg'])) {                                          
                                            $childpotion = $child->getResource()->getAttribute('kg')->getFrontend()->getValue($child); ?>
                                            <option value="<?= $childpotion ?>"><?= $childpotion ?></option>
                                            <? }
                                            if(isset($child['grams'])) {  
                                                $childpotion = $child->getResource()->getAttribute('grams')->getFrontend()->getValue($child); ?>
                                               <option value="<?= $childpotion ?>"><?= $childpotion ?></option>
                                            <?php }
                                            if(isset($child['litre'])) {  
                                                $childpotion = $child->getResource()->getAttribute('litre')->getFrontend()->getValue($child); ?>
                                                <option value="<?= $childpotion ?>"><?= $childpotion ?></option>

                                           <?php } 
                                            }
                                          } ?>
                                         </select> 
                                        <?php }?>

                                </td>
                                <td>
                                    <button type="button" value="update_qty" name="update_cart_action" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-dec"  class="cart-less decreaseQty-<?= /* @escapeNotVerified */ $_item->getId() ?>">-</button>
                                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qtys"
                                        name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                        data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                        value="1"
                                        type="number"
                                        min="1"
                                        size="4"
                                        step="any"
                                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                        class="input-text qty"
                                        oninput="this.value=(parseInt(this.value))"
                                        data-validate="{required:true,'validate-greater-than-zero':true}" 
                                        data-role="cart-item-qty"/>                                  
                                    <button type="button" value="update_qty" name="update_cart_action" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-upt" class="cart-more increaseQty-<?= /* @escapeNotVerified */ $_item->getId() ?>">+</button>                  
                                </td>
                                <td>
                                    <?= $block->getProductPriceHtml($_item, $type) ?>                           
                                </td>
                                <td>
                                    <div class="quick product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                    <?= $block->getBlockHtml('formkey') ?>
                                                                    <?php if($_item->getTypeId() == 'simple'){ ?>
                                                                        <button type="submit"
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                            class="action tocart primary">
                                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                                        </button>
                                                                            <?php } else { ?>
                                                                            <a href="<?php echo  $newurl1;?>" class="action tocart primary">
                                                                                <span> Add to Cart </span>
                                                                            </a>
                                                                    <?php } ?>
                                                        </form>
                                                <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </td>
                                <?php } ?>
                                </tr>
                            <?php endforeach;  ?>
                    </table>
                </ol>
        </div>
          <?= $block->getPagerHtml() ?>
    </div>
</div>
<?php endif;?>
<script>
require(["jquery"],function($){
    $('.cart-more').click(function(){
        var val = $(this).siblings('.input-text.qty').attr('id');
         var curr=$(this).siblings('.input-text.qty').val();
         var newAdd = parseInt(curr)+parseInt(1);
         $(this).siblings('.input-text.qty').val(newAdd);
    });
    $('.cart-less').click(function(){
        var val = $(this).siblings('.input-text.qty').attr('id');
         var curr=$(this).siblings('.input-text.qty').val();
         var a=1;
         if(curr >a){
             var newAdd = parseInt(curr)-parseInt(1);
             $(this).siblings('.input-text.qty').val(newAdd);
         }
    });
});
</script>
<style>
tr.header-quick-order {
    background-color: #ececfd;
    padding: 5px;
    color: #000;
}
tr.header-quick-order th {
    font-weight: 500;
    font-size: 14px;
    color: #000000;    padding: 21px 5px;
}
.product-item-quick span.product-image-container {
    width: 50px !important;
}
.product-item-quick a.product-item-link {
    display: inline;
    color: #000;
    font-size: 14px;
}
.product-item-quick .product-item-name {
    display: inline;
}
.product-item-quick .product-item-name {
    display: block;
    padding: 10px 0px;    font-weight: 500;
}
.product-item-quick .product-item-details{padding:10px;}
.product-item-quick {
    display: flex;
}
#quick-order .price-box .price {
    color: #5bc448;
    font-family: domine;
    padding:10px 0px;    font-size: 18px !important;font-weight: 700;
}
#quick-order .price-box.price-final_price {
    padding: 10px 0px;
}
#quick-order a.action.tocart.primary,#quick-order .stock.unavailable {
    padding: 14px 20px;
    border-radius: 0px !important;
}
#quick-order .product-item-actions {margin:0px;}
tr.body-quick-order td {
    border-bottom: 1px solid #d7d7d7;
}
body.cms-quick-order .breadcrumbs {
    display: none;
}
#quick-order .input-text.qty {
    display: inline;
    width: 40px;
}
#quick-order .cart-less,#quick-order .cart-more {
    border: none;
    background: none;box-shadow:none;
}
tr.body-quick-order td {
	    font-size: 14px;
}
#quick-order span.price-label{display:none;}
select#weightoption {
    max-width: 70%;
}
#quick-order .price-box .old-price .price {
    color: #888;
    text-decoration: line-through;
}
</style>
