<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$taurl = $storeManager->getStore(2)->getCurrentUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$enurl = $storeManager->getStore(1)->getCurrentUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); 
$taurl=str_replace("?___from_store=web","",$taurl);
$enurl=str_replace("?___from_store=web","",$enurl);

if($_SERVER['REQUEST_URI'] == 'customer/account/login'){ 
	$taurl = "http://ne2.ulamart.com/ta/customer/account/login";
	$enurl = "http://ne2.ulamart.com/customer/account/login";	
} 
if($_SERVER['REQUEST_URI'] == 'customer/account'){ 
	$taurl = "http://ne2.ulamart.com/ta/customer/account";
	$enurl = "http://ne2.ulamart.com/customer/account";
 } ?>
 <li> <a class="enurl" href="<?php echo $enurl;?>">English /</a><a class="taurl" href="<?php echo $taurl;?>"> தமிழ்</a> </li>