<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */

?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getStoreId();
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>

<?php $_product = $block->getProduct();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <?php $ccsku = $_product->getSku(); ?>
<div class="popup-cart-custom popup-cart-custom-<?php echo $ccsku;?>" style="display: none;">
<p class="popup-success"> You added <span><?php echo $_product->getName();?></span> to your shopping cart.</p>
    <div class="pop-related-btn">
        <a class="action" href="<?php if($storeid == 2) {echo $baseUrl."ta/";}else {echo $baseUrl;} ?>checkout/cart">View Cart</a>
        <button class="action" type="button" data-role="action"><span>Continue Shopping</span></button>
    </div>
        <?php 
        $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
        $relatedProducts = $product->getRelatedProducts();
        if (!empty($relatedProducts)) { ?>
                <h3> You might also like </h3>
                <div class="rel-pro">
            <?php 
            $ii = 1;
            foreach ($relatedProducts as $relatedProduct) {
                if ($ii <= 3) {
                    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($relatedProduct->getId()); ?>
                       <?php if($_product->getVisibility() == 4) { ?>
                    <div class="related-img">
                    <a class="you-might-also-like" href="<?php echo $_product->getProductUrl();?>" target="_blank"><img src="<?php echo $baseUrl;?>pub/media/catalog/product/<?php echo $_product->getData('small_image');?>"></a>   
                    <?php $name= $_product->getName();?>                
                    <p class="related-name">
                        <a class="you-might-also-like" href="<?php echo $_product->getProductUrl();?>" target="_blank">
                            <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                <?php echo $name = strlen($name ) > 50 ? substr($name ,0,30)."..." : $name ;?>
                            <?php } else {
                                echo $name;
                            } ?>
                        </a>
                    </p>
                    </div>
                 <?php 
                       }
                }
             $ii++;
            } ?>
            </div>
        <?php }  ?>
</div>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <?php if(($storeid == 1) || ($storeid == 0)) { ?>
         <label class="label" for="qty"><span><?= $block->escapeHtml(__('Quantity')) ?></span></label>
        <?php } else { ?>
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('அளவு')) ?></span></label>
       <?php  } ?>
        <div class="field qty">  
            <div class="control">
            <input type="button" class="custom-less" value="-"/>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>" readonly
                       />
                <input type="button" class="custom-more" value="+"/>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"> <img src="<?php echo $baseUrl;?>pub/media/custom-product/cart.png">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
        <div class="buy-now-block">
            <button type="button"
                    title="buy now"
                    class="action primary buynow"
                    id="product-buynow-button">
                    <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                        <label class="label" for="qty"><span>Buy Now</span></label>
                    <?php } else { ?>
                        <label class="label" for="qty"><span>இப்போதே வாங்குக</span></label>
                    <?php  } ?>
            </button>
        </div>
    </div>
</div>
 <!-- custom -->
 <?php $cult = $_product->getData('cultivation');?>
             <?php echo $cult; ?> 
<!-- custom -->
 <!-- custom success message -->
 <div class="page messages mobile"><div data-placeholder="messages"></div>
    <div data-bind="scope: 'messages'">
        <!-- ko if: cookieMessages && cookieMessages.length > 0 -->
        <div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message',
                'data-ui-id': 'message-' + message.type
            }">
                <div data-bind="html: message.text"></div>
            </div>
        </div>
        <!-- /ko -->
        <!-- ko if: messages().messages && messages().messages.length > 0 -->
        <div role="alert" data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages">
            <div data-bind="attr: {
                class: 'message-' + message.type + ' ' + message.type + ' message',
                'data-ui-id': 'message-' + message.type
            }">
                <div data-bind="html: message.text"></div>
                <!-- <div class="message-close"></div> -->
            </div>
        </div>
        <!-- /ko -->
    </div>
</div>
<!-- custom success message -->
<!-- sticky add to cart -->
<?php $_finalPrice = $_product->getFinalPrice(); 
$_finalPrice = $_finalPrice + 0;
?>

<div class="ss-mob-cart">
    <div class="row">
          <div class="ss-qty-prc">
                <div class="ss-pro-qty"></div>
                <div class="ss-pro-price"></div>
                <?php $ptype = $_product->getTypeId();?>
                <?php  if($ptype=='simple'){ ?>
                    <div class="ss-pro-price1"><?php echo "₹".$_finalPrice; ?></div>
                <?php } ?>
            </div>
           
            <div class="ss-add">
                <div class="ss-cart-btns">
                    <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart" >
                    <span><img src="<?php echo $baseUrl;?>pub/media/custom-product/cart.png"> <?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                </div>
            </div>
            <div class="ss-fav">
            <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"> <img src="<?php echo $baseUrl;?>pub/media/home/wishlist.png"></a>  
            </div>
    </div>
</div>
<!-- sticky add to cart -->
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
    
</script>
<script>
    require(["jquery"],function($){
        $('.custom-less').on('click', function () {
            var a=1;
            var input = jQuery('#qty');
            var str= parseInt(jQuery("#qty").val());
                if(str >a){
                  input.val(parseFloat(input.val()) - 1);
                }
        });

        $('.custom-more').on('click', function () {
            var input = jQuery('#qty');
            input.val(parseFloat(input.val()) + 1);
        });
});
</script>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "messages": {
                            "component": "Magento_Theme/js/view/messages"
                        }
                    }
                }
            }
    }
</script>
<script type="text/x-magento-init">
    {
        "#product-buynow-button": {
            "catalogBuyNow": {
                "form": "#product_addtocart_form",
                "redirectUrl": "<?php echo $this->getUrl('checkout')?>"
            }
        }
    }
</script>
<script>
    require(["jquery"],function($){
        $('#product-buynow-button').on('click', function () {
            $('#product-buynow-button span').text('Adding...')

        });
    });
</script>