<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<!-- <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.13.0/css/all.css"> -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
</head>
<!-- currency switcher -->
<?php 
$curl = curl_init();
function getUserIpAddr(){
    if(!empty($_SERVER['HTTP_CLIENT_IP'])){
        //ip from share internet
        $ip = $_SERVER['HTTP_CLIENT_IP'];
    }elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
        //ip pass from proxy
        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
    }else{
        $ip = $_SERVER['REMOTE_ADDR'];
    }
    return $ip;
}
$realip=getUserIpAddr();
curl_setopt_array($curl, array(
//   CURLOPT_URL => "http://ip-api.com/json/".$realip,
CURLOPT_URL => "https://ipinfo.io/".$realip."/json",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
));

$response = curl_exec($curl);
$response_value = json_decode($response);
$countryCode = $response_value->country;
?><p style="display:none" class="ulamart-cid"><?php echo $countryCode;?></p> <?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
if ($countryCode == "US") {
    $currency = "USD";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "$";
    } 
}elseif ($countryCode == "IN") {
    $currency = "IN";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "₹";
    } 
}elseif ($countryCode != "US") {
    $currency = "IN";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "₹";
    }
}
?>
<p style="display:none" class="ulamart-csymbol"><?php echo $currencySymbol;?></p>
<!-- currency switcher -->
<?php if ($block->getShowPart() == 'welcome') : ?>
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in"
              data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>

<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>
