<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
<?php
$product = $block->getProduct(); ?>
<?php $_finalPrice = $product->getFinalPrice(); 
$_price = $product->getPriceInfo()->getPrice('regular_price')->getValue(); 
if($_finalPrice < $_price):
$saveprice = $_price - $_finalPrice ;
$_savingPercent = 100 - round(($_finalPrice / $_price)*100);
echo '<div class="discount-label"><img src="'.$baseUrl.'pub/media/home/discount_icon.png"><p class="disc off">You Save <span><strong>₹'.$saveprice.'</strong> (Special offer : <strong>'.$_savingPercent.'% </strong> OFF)</span></p></div>'; ?>
<?php endif; ?>
