<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$storeid = $storeManager->getStore()->getStoreId();
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $tittle=$block->getTitle(); 
    
        $items = $block->getProductCollection()->getItems();
        // $items =  $items->addAttributeToSort('position','ASC');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
        <?php 
    $tittle = $block->getTitle(); 
    if ($tittle=="bestseller") {
        $jj =111;
    } else {
        $jj =1;
    }
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>

        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item normal">' : '</li><li class="product-item normal">' ?>
                        <div class="product-item-info">
                    <!-- custom place -->
                     <?php if ($showWishlist || $showCompare || $showCart) : ?>

                        <div class="show-wish custom">
                                <div class="product-item-actions custom">
                                       <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php //phpcs:disable ?>
                                                 <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                 <?php //phpcs:enable ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                 <?php endif; ?>
                                             </div>
                                        <?php endif; ?>
                                </div>
                        </div>
                    <?php endif; ?>
                     <!-- custom place -->
                                    <!-- custom category path -->
                                    <?php $categories = $_item->getCategoryIds(); /*will return category ids array*/
                                        $j = 0;
                                        foreach($categories as $key => $category){     
                                        $j++;
                                        $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                        $j++;
                                        $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                        $cid = $cat->getId();
                                          if(($cid != 27) && ($cid != 2) && ($cid != 22) && ($cid != 23)) {
                                             $catl = $cat->getUrl();
                                        }
                                       } 
                                       $newurl1 = $catl."/".$_item->getUrlKey(); 
                                       ?> 
                                     <!-- custom  category path -->
                            <a href="<?= $newurl1; ?>" class="product-item-photo" >
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <!-- custom cart -->
                            <div class="customs product-item-actions">
                                    <?php if ($showCart) : ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()) : ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <?php if($_item->getTypeId() == 'simple'){ ?>
                                                        <a href="javascript:void(0)" id="simple-action-addToCart" class="action tocart primary s" role="button"><span class="<?php echo $_item->getId(); ?>">Add to Cart</span></a>
                                                        <?php } elseif (($_item->getTypeId() != 'configurable') && ($_item->getTypeId() != 'simple')){ ?>
                                                            <a href="<?php echo  $newurl1;?>" class="action tocart primary non">
                                                            <span> Add to Cart </span>
                                                            </a>
                                                        <?php } ?>
                                                </form>
                                                      <!-- quick add -->
                                                        <?php  if ($_item->getTypeId() == 'configurable') {
                                                            $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
                                                            $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
                                                            $currencySymbol = $currency->getCurrencySymbol(); 
                                                                if ($_item->isAvailable()) {?>
                                                                    <figcaption class="card-figcaption">
                                                                        <span class="parent-id" style="display:none;"><?php echo $_item->getId(); ?></span>
                                                                            <div class="card-figcaption-bottom">
                                                                                <a href="javascript:void(0)" data-event-type="product-click" class="button button--small button-quickShop quickadd-<?php echo $_item->getId(); ?>" id="<?php echo $_item->getId(); ?>"><span>ADD TO CART </span></a>
                                                                            </div>
                                                                            <div class="quickShopPopup scrollbar"></div>
                                                                    </figcaption>
                                                                <?php }
                                                            } ?>
                                                     <!-- quick add -->
                                                       <?php else : ?>
                                                           <?php if ($_item->getIsSalable()) : ?>
                                                               <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                           <?php else : ?>
                                                               <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                           <?php endif; ?>
                                                       <?php endif; ?>
                                                   </div>
                                               <?php endif; ?>
                             </div>
                               <!-- custom cart -->
                            <div class="product-item-details">
                                <strong class="product-item-name ss">
                                    <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                       href="<?= $newurl1; ?>"
                                       class="product-item-link" >
                                       <?php $name= strtolower($block->escapeHtml($_item->getName()));?>
                                       <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                <?php echo $name = strlen($name ) > 50 ? substr($name ,0,43)."..." : $name ;?>
                                <?php } else {
                                  echo $name;
                                } ?>
                                    </a>
                                </strong>
                                <div class="new-price-block">
                                    <!-- custom code for configure -->
                                    <?php $ptype = $_item->getTypeId();?>
                                    <?php  if($ptype=='configurable'): ?>
                                        <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                        <?php $product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_item->getId()); ?>
                                        <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                        $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product); ?>
                                        <!-- new code -->
                                        <?php 
                                            $_children = $product->getTypeInstance()->getUsedProducts($product);
                                            $attributeValue1=[];
                                            $attributeValue2=[];
                                            $attributeValue3=[];
                                            $cweight_array=[];
                                            foreach ($_children as $child){ 
                                                $cweight1 = $child->getWeight();
                                                array_push($cweight_array,$cweight1);
                                                $attribute1 = $child->getResource()->getAttribute('grams');
                                                $attribute2 = $child->getResource()->getAttribute('kg');
                                                $attribute3 = $child->getResource()->getAttribute('litre');
                                            // Get Value
                                            array_push($attributeValue1,$attribute1->getFrontend()->getValue($child)); 
                                            array_push($attributeValue2,$attribute2->getFrontend()->getValue($child)); 
                                            array_push($attributeValue3,$attribute3->getFrontend()->getValue($child)); 
                                            // Get Label
                                            $attributeLabel1 = $attribute1->getStoreLabel(); 
                                            $attributeLabel2 = $attribute2->getStoreLabel();
                                            $attributeLabel3 = $attribute3->getStoreLabel(); ?>
                                        <?php }?>
                                        <p style="display:none;"><?php
                                        asort($cweight_array);
                                        $new_weight=array();
                                        foreach($cweight_array as $x => $x_value) {
                                            array_push($new_weight,$x_value);
                                        }
                                        
                                            ?> </p>
                                            <span class="custom-kg widget">
                                            <?php 
                                            if(isset($new_weight) && count($new_weight)>0){
                                                $cc = $new_weight[0];
                                                if ($cc == 0.10000) {
                                                    $cc = 100;
                                                }
                                                if ($cc == 0.50000) {
                                                    $cc = 0.5;
                                                }
                                                if ($cc == 0.050000) {
                                                    $cc = 50;
                                                }
                                                if ($cc == 0.25000) {
                                                    $cc = 0.25;
                                                }
                                                if ($cc == 0.02500) {
                                                    $cc = 0.025;
                                                }
                                                if ($cc == 0.01000) {
                                                    $cc = 0.01;
                                                }
                                                if ($cc == 0.03000) {
                                                    $cc = 0.03;
                                                }
                                                if ($cc == 0.3000) {
                                                    $cc = 0.3;
                                                }
                                                if(isset($attributeValue1) && count($attributeValue1)>0){ 
                                                    $result = preg_replace('/\b\d+\b/', '', $attributeValue1[0]);
                                                    if($result!='')
                                                        $result=$cc.str_replace('.','',$result); 
                                                        echo $result;
                                                    
                                                }  
                                                if(isset($attributeValue2) && count($attributeValue2)>0){ 
                                                    $result = preg_replace('/\b\d+\b/', '', $attributeValue2[0]);
                                                    if($result!='')

                                                        $result=$cc.str_replace('.','',$result); 
                                                        echo $result;
                                                } 
                                                if(isset($attributeValue3) && count($attributeValue3)>0){ 
                                                    $result = preg_replace('/\b\d+\b/', '', $attributeValue3[0]);
                                                    if($result!='')

                                                        $result=$cc.str_replace('.','',$result); 
                                                        echo $result;
                                                } 
                                            } ?>
                                             : </span>
                                            <!-- new code -->
                                        <?php endif ?>
                                        <!-- custom code for configure -->
                                        <?= $block->getProductPriceHtml($_item, $type) ?>
                                </div>
                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach;  ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
<script>
require(["jquery"],function($){
    // show variant
 jQuery('a.button-quickShop').click(function(){
        var elmId = jQuery(this).attr("id");
        $ = jQuery;
        $('.product-item-actions').removeClass("is-open");
        $('.quickShopPopup.scrollbar.is-open').removeClass('is-open');
        $('.product-item-details').removeClass("is-open");
        $('.quickShopPopup.scrollbar .halo-quickShop').remove();
        $('.card-figcaption.is-open').removeClass('is-open');
        $(this).children("span").css("display", "none");
        $(this).append('<i class="fa fa-circle-o-notch fa-spin"></i>');
        var baseurl = "<?php echo $baseUrl; ?>";
        var pr_id= elmId;
         $.ajax({
            type: 'POST',
            url: baseurl+'helloworld/index/product',
            dataType: 'json',
            showLoader: false,
            cache: false,
            data: { 'pr_id' : pr_id},
            success : function(result){
                $("a.quickadd-"+elmId).children("span").css("display", "inline");
                $("a.quickadd-"+elmId).children("i").remove();
                $("a.quickadd-"+elmId).parent().parent().parent('.actions-primary').parent('.product-item-actions').addClass("is-open");
                $("a.quickadd-"+elmId).parent().parent().parent().parent('.product-item-actions').next('.product-item-details').addClass("is-open");
            var status = result.status;
            var option = result.option;
            var childid = result.childid;
            var cprice = result.cprice;
            var symb = "<?php echo $currencySymbol ?>";
            var attr = result.attr;
                if(status == '1')
                {  
                    $("a.quickadd-"+elmId).parent().next().addClass('is-open');
                    $("a.quickadd-"+elmId).parent().parent('.card-figcaption').addClass('is-open');
                    var quickview_data='<div class="halo-quickShop"><div class="form-field selected"><label class="form-label form-label--inlineSmall" id="rectangle-group-label"><span>'+option[0]+'</span>'+attr+'<small> : '+symb+cprice[0]+'</small></label>';
                    for(var ss=0;ss < option.length;ss++){
                        if(ss == 0) {
                            var dem = '<div class="form-option-wrapper"> <input class="form-radio" checked type="radio" id="attribute_rectangle__'+childid[ss]+'" name="'+cprice[ss]+'" value="'+childid[ss]+'"> <label class="form-option"><span class="form-option-variant">'+option[ss]+'</span></label></div>';
                            quickview_data += dem;
                        } else {
                            var dem = '<div class="form-option-wrapper"> <input class="form-radio" type="radio" id="attribute_rectangle__'+childid[ss]+'" name="'+cprice[ss]+'" value="'+childid[ss]+'"> <label class="form-option"><span class="form-option-variant">'+option[ss]+'</span></label></div>';
                            quickview_data += dem;
                        }
                        
                    }
                    quickview_data +='</div><div class="action-quick-btn"><div id="add-to-cart-wrapper-quick"><div class="form-action"><a href="javascript:void(0)" id="form-action-addToCart" class="button button--tertiary" role="button">SUBMIT</a></div></div><div class="halo-quickShop-action"><a href="javascript:void(0)" class="button halo-quickShop-close" aria-label="'+elmId+'" role="button"> <span>CANCEL</span></a></div></div></div>';
                    $("a.quickadd-"+elmId).parent().next().html(quickview_data);
                }
                else{
                    $("a.quickadd-"+elmId).parent().next().removeClass('is-open');
                }
            }
        });
    });
    // close variant
    $( "body" ).delegate( "a.halo-quickShop-close", "click", function() {
           var clsid = jQuery(this).attr("aria-label");
            $("a.quickadd-"+clsid).parent().next().find('.halo-quickShop').remove();
            $("a.quickadd-"+clsid).parent().parent('.card-figcaption').removeClass('is-open');
            $("a.quickadd-"+clsid).parent().parent().parent().parent('.product-item-actions').removeClass("is-open");
            $("a.quickadd-"+clsid).parent().parent().parent().parent('.product-item-actions').next('.product-item-details').removeClass("is-open");
    });
     // change variant
     $( "body" ).delegate( "label.form-option", "click", function() {
        $('.halo-quickShop input.form-radio').prop( "checked", false );
        $(this).prev('input.form-radio').prop( "checked", true );
        $('#form-action-addToCart').text("SUBMIT");
        var cprice = $(this).prev('input.form-radio').attr("name");
        var variant = $(this).children('span').text();
        $(this).parents('.form-option-wrapper').parent('.form-field').addClass("selected");
        var symb = "<?php echo $currencySymbol ?>"; 
            $('.form-field.selected').children('label').find('span').text(variant);
            $('.form-field.selected').children('label').find('small').text(' : '+symb+cprice);
    });
    // setTimeout(function() {
    //     $('.page.messages').children().detach();
    // }, 5000);
});
</script>
<style>
body.cms-home .ui-tooltip{display: block;border: 1px solid #ededed;padding: 10px;position: absolute;z-index: 9999;bottom: 45px;width: max-content;left: 0px;}
.card-figcaption-bottom a i:nth-child(2) {display: none;}
body.cms-home .card-figcaption-bottom a{padding:9px 10px;}
body.cms-home .customs.product-item-actions .action.primary{border: 1px solid #fec104 !important;}
.page.messages .message.success>*:first-child:before{color: #f4a340;}
.page.messages .message.success{background: #fff4e6;color: #000;border: 1px solid #f4a340;font-weight: 500;}
.page.messages .message.success a{color: #d97d0c;}
@media only screen and (max-width:767px) {
    .page.messages div.message {position: fixed;top: 5px;z-index: 9999999;left: 5px;width: 97%;}
 }
 @media only screen and (min-width:768px) {
    body.cms-home .customs.product-item-actions .action.primary:hover {color: #000 !important;background-color: #fff !important;border: 1px solid #000 !important;}
    body.cms-home .products-grid .product-item-info:hover {padding-top: 0px !important;}
    body.cms-home .product-item-actions .actions-secondary>.action{line-height: 28px !important;}
    .page.messages div.message{position: fixed;top: 5px;z-index: 9999999;left: 10%;right: 10%;width: 80%;}
 } 
 body.cms-home .products-grid .product-item-info:hover {padding:0px 0px !important;}
</style>
