<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getStoreId();
$wishlist = $objectManager->get('\Magento\Wishlist\Model\Wishlist');
$customerSession = $objectManager->get('Magento\Customer\Model\SessionFactory')->create();
?>
<style>
    .action.towishlist.already-added:before{color: red !important;}
</style>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>      
    <?php $_product = $block->getProduct();          
    if($customerSession->isLoggedIn()){
        //getting customer ID
        $customerData = $customerSession->getCustomer()->getData(); //get all data of customerData
        $customerId = $customerSession->getCustomer()->getId();//get id of customer
        //Getting wishlist products Collections  Related to Customers
        $wishlist_collection = $wishlist->loadByCustomerId( $customerId , true)->getItemCollection();
        foreach ($wishlist_collection as $wishlist_product):
        if($_product->getId() == $wishlist_product->getProduct()->getId()){ ?>
            <a href="javascript:void(0)" class="action towishlist already-added" data-action="add-to-wishlist">
            <span><?= $block->escapeHtml(__('Added to Wish List')) ?></span>
            </a>
        <?php } elseif($_product->getId() != $wishlist_product->getProduct()->getId()) { ?>
            <a href="#"
        class="action towishlist no"
        title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
        aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
        data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
        data-action="add-to-wishlist"
        role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>
        <?php } 
        endforeach; ?>
    <?php } else { ?>
        <a href="#"
        class="action towishlist nlog"
        title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
        aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
        data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
        data-action="add-to-wishlist"
        role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>
    <?php } ?>
<?php endif; ?>



