<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
<div data-role="loader" class="loading-mask">
    <div class="loader">

        <img src="<?php echo $block->getGalleryImages()->getFirstItem()->getData('medium_image_url') ?>" style="max-width: 100%; max-height: 100%">
    </div>
</div>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
var config = {
        "width": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                    ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
        "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>
    },
    thumbBarHeight = 0,
    loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

if (config.navtype === 'horizontal') {
    thumbBarHeight = config.thumbheight;
}

loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
{
    "[data-gallery-role=gallery-placeholder]": {
        "mage/gallery/gallery": {
            "mixins":["magnifier/magnify"],
            "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
            "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
            "options": {
                "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                <?php if (($block->getVar("gallery/loop"))): ?>
                    "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                <?php endif; ?>
                <?php if (($block->getVar("gallery/keyboard"))): ?>
                    "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                <?php endif; ?>
                
                <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                    "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                <?php endif; ?>
                
                "width": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
                "thumbwidth": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'width'); ?>",
                <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                    "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                    ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                <?php endif; ?>
                <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                    "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                    ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                <?php endif; ?>
                <?php if ($block->getVar("gallery/transition/duration")): ?>
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                <?php endif; ?>
                "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
               
                "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>"
            },
            "fullscreen": {
                "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                    "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                <?php endif; ?>
                "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
               
                "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navtype"); ?>",
                
                
                <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                    "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                <?php endif; ?>
                "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
            },
            "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
        }
    }
}
</script>

<style>
.loader img:first-child {
    background-color: #fff;
    width: auto;
    top: 7.5%;
    left: 20.4%;
    position: absolute;
    height: auto;
    max-height: 100%;
    max-width: 100%;
    vertical-align: middle;
    border: 1px solid rgba(214,235,239,0.5) !important;
}
.gallery-placeholder._block-content-loading .loading-mask{position: relative;}
@media only screen and (min-width: 768px) {
    .gallery-placeholder__image {
    margin-top: 57px;
    width: auto;
    }
}
body .gallery-placeholder__image {
   height: auto;color:#fff !important;
   max-height: 100%;
   max-width: 100%;
   position: absolute;background-color:#fff;
}
.fotorama__wrap .fotorama__arr,.fotorama__caption__wrap {
    display: none!important;
}
@media only screen and (max-width:1330px) {
.loader img:first-child {width: 70%;left: 19%;}
}
@media only screen and (max-width: 767px) {
body.catalog-product-view .gallery-placeholder {max-width:100% !important;}
}
@media only screen and (max-width: 767px) and (min-width: 425px) {
	.gallery-placeholder._block-content-loading .loading-mask{padding-bottom:81% !important;}
}
@media only screen and (max-width: 425px) {
.gallery-placeholder._block-content-loading .loading-mask{padding-bottom:90% !important;}
}
</style>