<?php
// customer custom code                    
        $curl = curl_init();

          curl_setopt_array($curl, array(
          CURLOPT_URL => 'https://api.interakt.ai/v1/public/track/users/',
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'POST',
          CURLOPT_POSTFIELDS =>'{
           "userId": "'.$checkid.'",
          "phoneNumber": "'.$telephone.'",
          "countryCode": "+91",
          "traits": {
          "name": "'.$checkname.'",
          "email": "'.$checkem.'"
                    }
           }',
          CURLOPT_HTTPHEADER => array(
          'Content-Type: application/json',
          'Authorization: Basic UzQteTBVSmZvbzBsX2k4NFhWMUo1UXRfOExua2ZKd0ZRajNSNHZCLTM5STo='
            ),
          ));

          $response = curl_exec($curl);

          curl_close($curl);
          // customer custom code
           $curl = curl_init();


          curl_setopt_array($curl, array(
          CURLOPT_URL => 'https://api.interakt.ai/v1/public/track/events/',
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => '',
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => 'POST',
          CURLOPT_POSTFIELDS =>'{
            "userId":  "'.$checkid.'",
             "event": "OrderPlaced",
            "traits": {
                "orderCreatedBy":"'.$checkname.'",
                "orderNumber": "'.$curorderid.'",
                "orderValue":"'.$grandtotals.'",
                "currency": "INR"
                },
              "createdAt": "'.$currentdate.'"
              }',
            CURLOPT_HTTPHEADER => array(
              'Content-Type: application/json',
              'Authorization: Basic UzQteTBVSmZvbzBsX2k4NFhWMUo1UXRfOExua2ZKd0ZRajNSNHZCLTM5STo='
            ),
            ));
              
            $response = curl_exec($curl);
              
            curl_close($curl);
          // custom code
?>