<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>
<!-- currency switcher -->
<?php 
$curl = curl_init();
function getUserIpAddr(){
    if(!empty($_SERVER['HTTP_CLIENT_IP'])){
        //ip from share internet
        $ip = $_SERVER['HTTP_CLIENT_IP'];
    }elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])){
        //ip pass from proxy
        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
    }else{
        $ip = $_SERVER['REMOTE_ADDR'];
    }
    return $ip;
}
$realip=getUserIpAddr();
curl_setopt_array($curl, array(
//   CURLOPT_URL => "http://ip-api.com/json/".$realip,
CURLOPT_URL => "https://ipinfo.io/".$realip."/json",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "GET",
));

$response = curl_exec($curl);
$response_value = json_decode($response);
$countryCode = "US"; //$response_value->country;
?><p style="display:none" class="ulamart-cid"><?php echo $countryCode;?></p> <?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
if ($countryCode == "US") {
    $currency = "USD";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "$";
    } 
}elseif ($countryCode == "IN") {
    $currency = "USD";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "₹";
    } 
}elseif ($countryCode != "US") {
    $currency = "USD";
    if ($currency) {
        $storeManager->getStore()->setCurrentCurrencyCode($currency);
        $currencySymbol = "₹";
    }
}
?>
<p style="display:none" class="ulamart-csymbol"><?php echo $currencySymbol;?></p>
<!-- currency switcher -->
<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<a
    class="logo"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
    />
</a>
