<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */

/* Remove 'Grand Total to be Charged' block from totals */
$block->removeTotal('base_grandtotal');
?>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceInterface = $objectManager->create('Magento\Framework\Pricing\PriceCurrencyInterface');
$ssmbol = $this->getOrder()->getOrderCurrencyCode(); ?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php 
    if ($ssmbol == 'USD'){
        if ($_code == 'subtotal'){$_total->setValue($_total->getValue()+$this->getOrder()->getTaxAmount());} ?>
    <style>
    .totals-tax {display:none;}
    </style>
    <?php } ?>
    <?php if ($_total->getBlockName()) : ?>
        <?= $block->getChildHtml($_total->getBlockName(), false) ?>
    <?php else :?>
    <tr class="<?= $block->escapeHtmlAttr($_code) ?>">
        <th <?= /* @noEscape */ $block->getLabelProperties() ?> scope="row">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= $block->escapeHtml($_total->getLabel()) ?></strong>
            <?php else : ?>
                <?= $block->escapeHtml($_total->getLabel()) ?>
            <?php endif ?>
        </th>
        <td <?= /* @noEscape */ $block->getValueProperties() ?> data-th="<?= $block->escapeHtmlAttr($_total->getLabel()) ?>">
            <?php if ($_total->getStrong()) : ?>
                <strong><?= /* @noEscape */ $block->formatValue($_total) ?></strong>
            <?php else : ?>
                <?= /* @noEscape */ $block->formatValue($_total) ?>
            <?php endif?>
        </td>
    </tr>
    <?php endif; ?>
<?php endforeach?>
