<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getStoreId();
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $tittle=$block->getTitle(); 
    
        $items = $block->getProductCollection()->getItems();
        // $items =  $items->addAttributeToSort('position','ASC');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
        <?php 
    $tittle = $block->getTitle(); 
    if ($tittle=="bestseller") {
        $jj =111;
    } else {
        $jj =1;
    }
    ?>
    <div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
        <?php if ($block->getTitle()) : ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
            </div>
        <?php endif ?>

        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item) : ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item normal">' : '</li><li class="product-item normal">' ?>
                        <div class="product-item-info">
                    <!-- custom place -->
                     <?php if ($showWishlist || $showCompare || $showCart) : ?>

                        <div class="product-item-inner custom">
                                <div class="product-item-actions custom">
                                       <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php //phpcs:disable ?>
                                                 <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                 <?php //phpcs:enable ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                 <?php endif; ?>
                                             </div>
                                        <?php endif; ?>
                                </div>
                        </div>
                    <?php endif; ?>
                     <!-- custom place -->
                                    <!-- custom category path -->
                                    <?php $categories = $_item->getCategoryIds(); /*will return category ids array*/
                                        $j = 0;
                                        foreach($categories as $key => $category){     
                                        $j++;
                                        $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                        $j++;
                                        $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
                                        $cid = $cat->getId();
                                          if(($cid != 27) && ($cid != 2) && ($cid != 22) && ($cid != 23)) {
                                             $catl = $cat->getUrl();
                                        }
                                       } 
                                       $newurl1 = $catl."/".$_item->getUrlKey(); 
                                       ?> 
                                     <!-- custom  category path -->
                            <a href="<?= $newurl1; ?>" class="product-item-photo" >
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
 <!-- custom cart -->
 <div class="customs product-item-actions">
                                               <?php if ($showCart) : ?>
                                                   <div class="actions-primary">
                                                       <?php if ($_item->isSaleable()) : ?>
                                                           <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                           <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                               <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                               <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                               <?= $block->getBlockHtml('formkey') ?>
                                                               <?php if($_item->getTypeId() == 'simple'){ ?>
                                                                <button type="submit"
                                                                       title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                       class="action tocart primary">
                                                                   <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                               </button>
                                                                <?php } else { ?>
                                                                <a href="<?php echo  $newurl1;?>" class="action tocart primary">
                                                                <span> Add to Cart </span>
                                                                </a>
                                                                <?php } ?>
                                                           </form>
                                                       <?php else : ?>
                                                           <?php if ($_item->getIsSalable()) : ?>
                                                               <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                           <?php else : ?>
                                                               <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                           <?php endif; ?>
                                                       <?php endif; ?>
                                                   </div>
                                               <?php endif; ?>
                                           </div>
                               <!-- custom cart -->
                            <div class="product-item-details">
                                <strong class="product-item-name ss">
                                    <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                       href="<?= $newurl1; ?>"
                                       class="product-item-link" >
                                       <?php $name= $block->escapeHtml($_item->getName()) ?>
                                       <?php if(($storeid == 1) || ($storeid == 0)) { ?>
                                <?php echo $name = strlen($name ) > 50 ? substr($name ,0,43)."..." : $name ;?>
                                <?php } else {
                                  echo $name;
                                } ?>
                                    </a>
                                </strong>
                                <?php if ($templateType) : ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?= $block->getProductPriceHtml($_item, $type) ?>
                                <!-- custom code for configure -->
                                <?php $ptype = $_item->getTypeId();?>
                                <?php  if($ptype=='configurable'): ?>
                                    <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                    <?php $product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_item->getId()); ?>
                                    <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
                                    $productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($product); ?>
                                    <!-- new code -->
                                    <?php 
                                         $_children = $product->getTypeInstance()->getUsedProducts($product);
                                         $attributeValue1=[];
                                         $attributeValue2=[];
                                         $attributeValue3=[];
                                         $cweight_array=[];
                                        foreach ($_children as $child){ 
                                            $cweight1 = $child->getWeight();
                                            array_push($cweight_array,$cweight1);
                                            $attribute1 = $child->getResource()->getAttribute('grams');
                                            $attribute2 = $child->getResource()->getAttribute('kg');
                                            $attribute3 = $child->getResource()->getAttribute('litre');
                                        // Get Value
                                        array_push($attributeValue1,$attribute1->getFrontend()->getValue($child)); 
                                        array_push($attributeValue2,$attribute2->getFrontend()->getValue($child)); 
                                        array_push($attributeValue3,$attribute3->getFrontend()->getValue($child)); 
                                        // Get Label
                                        $attributeLabel1 = $attribute1->getStoreLabel(); 
                                        $attributeLabel2 = $attribute2->getStoreLabel();
                                         $attributeLabel3 = $attribute3->getStoreLabel(); ?>
                                       <?php }?>
                                       <p style="display:none;"><?php
                                       asort($cweight_array);
                                       $new_weight=array();
                                       foreach($cweight_array as $x => $x_value) {
                                        array_push($new_weight,$x_value);
                                      }
                                       
                                        ?> </p>
                                         <span class="custom-kg widget">
                                        <?php 
                                        if(isset($new_weight) && count($new_weight)>0){
                                            $cc = $new_weight[0];
                                            if ($cc == 0.10000) {
                                                $cc = 100;
                                            }
                                            if ($cc == 0.50000) {
                                                $cc = 0.5;
                                            }
                                            if ($cc == 0.25000) {
                                                $cc = 0.25;
                                            }
                                            if ($cc == 0.02500) {
                                                $cc = 0.025;
                                            }
                                            if ($cc == 0.01000) {
                                                $cc = 0.01;
                                            }
                                            if(isset($attributeValue1) && count($attributeValue1)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue1[0]);
                                                if($result!='')
                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                                
                                            }  
                                            if(isset($attributeValue2) && count($attributeValue2)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue2[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                            if(isset($attributeValue3) && count($attributeValue3)>0){ 
                                                $result = preg_replace('/\b\d+\b/', '', $attributeValue3[0]);
                                                if($result!='')

                                                    $result=$cc.str_replace('.','',$result); 
                                                    echo $result;
                                            } 
                                        } ?>
                                        </span>
                                        <!-- new code -->
                               <?php endif ?>
                                <!-- custom code for configure -->
                                 <!-- sale countdown -->
                                 <?php if($_item->getTypeId() == 'simple'){ 
                                            $date = date_default_timezone_set('Asia/Kolkata');
                                            $chekdate = date('Y/m/d H:i:s');
                                            $currentDate =  date('d-m-Y');
                                            $todate      =  $_item->getSpecialToDate();
                                            $fromdate    =  $_item->getSpecialFromDate();
                                            $newcurrent  =  date('Y-m-d');     
                                            if($_item->getSpecialPrice() != 0 || $_item->getSpecialPrice()) {
                                                if($_item->getSpecialToDate() != null) {
                                                    if(strtotime($todate) >= strtotime($currentDate) && strtotime($fromdate) <= strtotime($currentDate)){ 
                                                        if(strtotime($todate) == strtotime($currentDate)) {
                                                                $newtodate = $newcurrent . "T24:00:00";
                                                                $newtodate  =  str_replace(' ','',$newtodate);
                                                            }
                                                            else { 
                                                                $newtodate = str_replace('/','-',$_item->getSpecialToDate());
                                                                $newtodate  =  str_replace('00:00:00','T24:00:00',$newtodate);
                                                                $newtodate  =  str_replace(' ','',$newtodate);
                                                            }?>
                                                        <div id="countdowntimer" class="countdowntimer"><p style="color: #e66b6b;">Hurry up! sale end soon</p><span id="widget_date<?php echo $jj; ?>" class="widget_date"><span></div>
                                                        <script>
                                                        require([
                                                            'jquery',
                                                            'Emizentech_Countdown/js/jquery.countdownTimer'
                                                        ], function ($) {
                                                                    console.log('countdowntimer start');
                                                                    var var1 = "<?php echo $jj; ?>";
                                                                    $('#widget_date'+var1).countdowntimer({
                                                                        startDate : "<?php echo $chekdate; ?>",
                                                                        dateAndTime : "<?php echo $newtodate;?>",
                                                                        size : "lg",
                                                                        regexpMatchFormat: "([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})",
                                                            // 			regexpReplaceWith: "$1 days $2 hours $3 minutes $4 seconds REMAINING"        
                                                                        regexpReplaceWith: "<div><span>$1</span><span>days</span></div> <div><span>$2</span><span>hours</span></div> <div><span>$3</span><span>mins</span></div> <div><span>$4</span><span>secs</span></div>"
                                                                    });  
                                                            });
                                                        </script>
                                                        <?php $jj++;
                                                    }   
                                                }
                                            }  
                                        }
                                        ?>
                                        <!-- sale countdown -->

                            </div>
                        </div>
                        <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                    <?php endforeach;  ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
