<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$customerSession = $objectManager->create('Magento\Customer\Model\Session'); ?>
<small class="copyright">
    <span><?= $block->escapeHtml($block->getCopyright()) ?></span><span class="clink"><a href="<?php echo $baseUrl ?>privacy-policy" >  | Privacy policy </a><a href="<?php echo $baseUrl ?>terms-and-conditions-of-ulamart" >  | Terms of service</a><a href="#" >  | Do not sell my info. </a><a href="<?php echo $baseUrl ?>sitemap.xml" >  | Sitemap</a></span>
    <p class="footerlogo"> <a href="//www.dmca.com/Protection/Status.aspx?ID=6e94cbe4-fcb9-452d-b811-0d2a3141d96f"><img class="mplazyload" data-src="<?php echo $baseUrl;?>pub/media/home/footerlogo.png"></a></p>

</small>
