<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$storeid = $storeManager->getStore()->getStoreId();
$TaxHelper = $objectManager->get('Magento\Catalog\Helper\Data');
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $tittle=$block->getTitle(); 
    
    $items = $block->getProductCollection()->getItems();
    // $items =  $items->addAttributeToSort('position','ASC');

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
<div class="message-success success message" style="display:none;">
</div>
<div class="message-error error message" style="display:none;">
</div>
<div class="quick-order-widget block widget block-products-list <?= /* @noEscape */ $mode ?>">
    <div class="block-content">
         <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                 <ol class="product-items <?= /* @noEscape */ $type ?>">
                    <table class="table-quick-order">
                        <tr class="header-quick-order">
                            <th>Product Name</th>
                            <th>Weight</th>
                            <th style="text-align:center;">quantity</th>
                            <th>Total Price</th>
                            <th> </th>
                        </tr>

                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item) : ?>
                                <?php if($_item->getIsSalable()) { ?>
                                <tr class="body-quick-order">
                                <td class="action_detail">
                                    <div class="product-item-quick">
                                        <div class="product-item-photo-quick" style="width:60px;">
                                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                                <?= $block->getImage($_item, $image)->toHtml() ?>
                                            </a>
                                        </div>
                                        <div class="product-item-details">
                                            <strong class="product-item-name">
                                                    <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                            href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                            class="product-item-link">
                                                <?php $name= $block->escapeHtml($_item->getName()) ?>
                                                <?php echo $name ;?>
                                                </a>
                                            </strong>
                                        </div>
                                    </div>
                                </td>
                                <td class="action_drop">
                                <?php $ptype = $_item->getTypeId();?>
                                <?php  if($ptype=='configurable') { ?>
                                    <?php $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                                    <?php //$product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($_item->getId()); ?>
                                    <?php $productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable'); ?>
                                    <!-- new code -->
                                    <?php 
                                         $_children = $_item->getTypeInstance()->getUsedProducts($_item); ?>
                                         <select name="weightoption" id="weightoption">

                                        <?php  
                                        $ii = 1;
                                        foreach ($_children as $child){ 
                                              if($child->getIsSalable()) {
                                                $cprice = $TaxHelper->getTaxPrice($child, $child->getFinalPrice(), true);
                                                $cprice = round($cprice);
                                                if ( $ii == 1) {
                                                    $pid = $child->getId(); 
                                                }
                                                $childid = $child->getId(); 
                                                ?>

                                            <?php if(isset($child['kg'])) {                                          
                                            $childpotion = $child->getResource()->getAttribute('kg')->getFrontend()->getValue($child); ?>
                                                <option value="<?= $childid ?>" name="<?= $cprice ?>"><?= $childpotion ?></option>
                                            <?php 
                                             }
                                            if(isset($child['grams'])) {  
                                                $childpotion = $child->getResource()->getAttribute('grams')->getFrontend()->getValue($child);  ?>
                                                    <option value="<?= $childid ?>" name="<?= $cprice ?>"><?= $childpotion ?></option>
                                                <?php 
                                                 }
                                            if(isset($child['litre'])) {  
                                                $childpotion = $child->getResource()->getAttribute('litre')->getFrontend()->getValue($child);  ?>
                                                    <option value="<?= $childid ?>" name="<?= $cprice ?>"><?= $childpotion ?></option>
                                                <?php 
                                                 }
                                           $ii++;
                                            }
                                          } ?>
                                         </select> 
                                        <?php } else {?>
                                            <?php $pid = $_item->getId(); 
                                            $psku = $_item->getSku();
                                        } ?>

                                </td>
                                <td class="action_qty">
                                    <button type="button" value="update_qty" name="update_cart_action" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-dec"  class="cart-less decreaseQty-<?= /* @escapeNotVerified */ $_item->getId() ?>">-</button>
                                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qtys"
                                        name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                        data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                        value="1"
                                        type="number"
                                        min="1"
                                        size="4"
                                        step="any" style="display: inline;width: 40px;"
                                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                        class="input-text qty"
                                        oninput="this.value=(parseInt(this.value))"
                                        data-validate="{required:true,'validate-greater-than-zero':true}" 
                                        data-role="cart-item-qty" readonly/>                                  
                                    <button type="button" value="update_qty" name="update_cart_action" id="<?= /* @escapeNotVerified */ $_item->getId() ?>-upt" class="cart-more increaseQty-<?= /* @escapeNotVerified */ $_item->getId() ?>">+</button>                  
                                </td>
                                <td class="action_price">
                                <?php if ($_item->getTypeId() == 'simple') {
                                        $tprice = $TaxHelper->getTaxPrice($_item, $_item->getFinalPrice(), true);
                                        $fprice = round($tprice);
                                        $oldprice = $TaxHelper->getTaxPrice($_item, $_item->getPrice(), true);
                                        $oldprice = round($oldprice);

                                    } else {
                                        $fprice = round($_item->getFinalPrice());
                                        $oldprice = round($_item->getPrice());
                                    }?>
                                    <input type="hidden" name="oldp" id="oldp" value="<?php echo $fprice; ?>"></input>
                                    <div id="cusprice" class="price">₹<?php echo $fprice; ?></div>
                                    <?php  $csdt = "0000-01-01";
                                           $dcurrent =date('Y-m-d');
                                        if($_item->hasSpecialPrice()) { 
                                            $cdt = $_item->getSpecialToDate();
                                                if(empty($cdt)) {
                                                    $csdt = $dcurrent;
                                                } else {
                                                $csdt = date('Y-m-d',strtotime($cdt));
                                                }
                                                if ($csdt >= $dcurrent) { ?>
                                                    <span class="product-old-price">₹<?php echo $oldprice; ?></span>
                                                <?php
                                                } 
                                         } ?>
                                </td>
                                <td class="action_div">
                                
                                    <div class="quick product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <input type="hidden" name="qtyid" id="qtyid" value="<?php echo $_item->getId(); ?>"></input>
                                                    <input type="hidden" name="prodid" id="childid" value="<?php echo $pid; ?>"></input>
                                                                        <button 
                                                                            title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                            class="action tocart primary cc_btn">Add to Cart</button>
                                                        
                                                <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                            <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </td>
                                <?php } ?>
                                </tr>
                            <?php endforeach;  ?>
                    </table>
                </ol>
        </div>
          <?= $block->getPagerHtml() ?>
    </div>
</div>

<?php endif;?>
<div class="quick-order-summary" id="quick-order-summary">
<?php include('/home/ulamart/public_html/cartproduct.php'); 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
    $itemsCollection = $cart->getQuote()->getItemsCollection();
    $itemsVisible = $cart->getQuote()->getAllVisibleItems();?>
    <h2 class="head-title">Order Summary</h2>
    <div class="quick-cart-item">
        <table>
            <tbody>
            <?php 
            if(count($itemsVisible)) {
                $discount ="";
                $totaldiscount = 0;
                foreach($itemsVisible as $item) { ?>
                <?php $products = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                $cartoption =""; 
                if($products->getVisibility() == 1) {
                     if(isset($products['kg'])) {                                          
                        $cartoption = $products->getResource()->getAttribute('kg')->getFrontend()->getValue($products); 
                    }elseif(isset($products['grams'])) {                                          
                        $cartoption = $products->getResource()->getAttribute('grams')->getFrontend()->getValue($products); 
                    }elseif(isset($products['litre'])) {                                          
                        $cartoption = $products->getResource()->getAttribute('litre')->getFrontend()->getValue($products); 
                    }
                }?>
                    <tr class="product-list">
                       <td class="name"><?php echo $item->getName(); ?></td>
                       <td class="qty">(<?php if($cartoption != "") {echo $cartoption." x ".$item->getQty();} else {echo $item->getQty();} ?>)</td>
                       <?php  $cartprice = $TaxHelper->getTaxPrice($products, $products->getFinalPrice(), true);
                            $sdt = "0000-01-01";
                            $current =date('Y-m-d');
                       if($products->hasSpecialPrice()) { 
                           $discount = $TaxHelper->getTaxPrice($products, $products->getPrice(), true);
                           $totaldiscount += (round($discount)) - $cartprice;
                           $dt = $products->getSpecialToDate();
                           if(empty($dt)) {
                            $sdt = $current;
                           } else {
                           $sdt = date('Y-m-d',strtotime($dt));
                           }
                         } ?>

                       <td class="price">₹<?php echo $item->getQty()*round($cartprice); ?><span> <?php if ($sdt >= $current) { if($discount){ echo "₹".round($discount); } }?></span></td>
                       <td class="minicart-items">
                           <div class="secondary">
                                <input type="hidden" name="delid" id="delid" value="<?php echo $item->getProductId(); ?>"></input>
                                <button title="action delete" class="action delete cc_del_btn"><span data-bind="i18n: 'Remove'"></span></button>
                            </div>
                        </td>
                    </tr>            
            <? }   
            }
        ?>
        </tbody>
        </table>
    </div>
    <div class="quick-cart-total">
    <table>
        <tbody>
            <?php if(count($itemsVisible)) { ?>
                <?php if($totaldiscount > 0) {?>
                    <tr class="cart-total">
                        <td class="title">Offer Price  (Product’s Discount) &nbsp;&nbsp;&nbsp; &nbsp;:</td>
                        <td class="dis-total">₹<?php echo round($totaldiscount); ?></td>
                    </tr>
                <?php } ?>
                <tr class="cart-total">
                <?php $subTotal = $cart->getQuote()->getSubtotal();
                    $grandTotal = $cart->getQuote()->getGrandTotal(); ?>
                    <td class="title">Total Price (Payable Amount) &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;:</td>
                    <td class="quick-total">₹<?php echo round($grandTotal); ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    </div>
    <a class="quick-checkout" href="checkout">CHECKOUT</a>
</div>
<script>
require([ "jquery" ], function($) {
    $( "body" ).delegate( "body", "load", function() {
        // $('#quick-order-summary').load("https://dev.ulamart.com/cartproduct.php");
        $("#quick-order-summary").load(location.href+" #quick-order-summary>*","");

    });
});
</script>
<script>
require(["jquery"],function($){
    $('.cart-more').click(function(){
        var val = $(this).siblings('.input-text.qty').attr('id');
         var curr=$(this).siblings('.input-text.qty').val();
         var newAdd = parseInt(curr)+parseInt(1);
         $(this).siblings('.input-text.qty').val(newAdd);
         var oprice = $(this).parent().siblings('td.action_price').find('#oldp').val();
        $(this).parent().siblings('td.action_price').find('#cusprice').text("₹"+oprice * newAdd);

    });
    $('.cart-less').click(function(){
        var val = $(this).siblings('.input-text.qty').attr('id');
         var curr=$(this).siblings('.input-text.qty').val();
         var a=1;
         if(curr >a){
             var newAdd = parseInt(curr)-parseInt(1);
             $(this).siblings('.input-text.qty').val(newAdd);
             var oprice = $(this).parent().siblings('td.action_price').find('#oldp').val();
             $(this).parent().siblings('td.action_price').find('#cusprice').text("₹"+oprice * newAdd);


         }
    });
    $('select#weightoption').on('change', function() {
        var childid = this.value;
        $(this).parent().siblings('td.action_div').find('input#childid').val(childid);
        var nameprice = $('option:selected', this).attr('name');
        var cqty = $(this).parent().siblings('td.action_qty').find('.input-text.qty').val();
        $(this).parent().siblings('td.action_price').find('#cusprice').text("₹"+nameprice * cqty);
        $(this).parent().siblings('td.action_price').find('#oldp').val(nameprice);
    });
});
</script>
<script>
    require(["jquery"],function($){
    // function quickOrder(cprid) {
        jQuery('button.cc_btn').click(function(){
        var get_id = jQuery(this).siblings('input#childid').val();

        $ = jQuery;
        if(cprid == "") {
            var cprid = $(this).siblings('input#childid').val();
        }
        var baseurl = "<?php echo $baseUrl; ?>";
        // var ctrl = get_id;
        var ctrl = $(this).siblings('input#qtyid').val();
        var qty = $("#cart-"+ctrl+"-qtys").val();
        var pr_id= get_id;
         $.ajax({
            type: 'POST',
            url: baseurl+'helloworld/index/index',
            dataType: 'json',
            showLoader: true,
            cache: false,
            data: { 'pr_id' : pr_id, 'qty' : qty},
            success : function(result){
            var status = result.status;
            if(status == '1')
            {
                $(".message.success").css("display", "block");
                $(".message.success").text("Your Product added to your shopping cart. ");
                setTimeout(function(){
                $('.message.success').hide();
                }, 5000);
                $("#quick-order-summary").load(location.href+" #quick-order-summary>*","");
                require(['jquery','Magento_Customer/js/customer-data'], function ($,customerData) { 
                    var sections = ['cart'];
                        customerData.invalidate(sections);
                        customerData.reload(sections, true);

                });
            }
            else{
                $(".message.error").css("display", "block");
                 $(".message.error").text("Please try again Later.");
                 setTimeout(function(){
                $('.message.error').hide();
                }, 5000);
            }

            }
        });
        $(this).addClass("green");
        $(this).css("background-color","#31b41c");
        $(this).text("Added");
    });
    $( "body" ).delegate( "button.cc_del_btn", "click", function() {
        var get_ids = $(this).siblings('input#delid').val();
        var baseurl = "<?php echo $baseUrl; ?>";
        var prd_id= get_ids;
         $.ajax({
            type: 'POST',
            url: baseurl+'helloworld/index/rcart',
            dataType: 'json',
            cache: false,
            data: { 'prd_id' : prd_id},
            success : function(result){
            var status = result.status;
            if(status == '1')
            {
                $(".message.success").css("display", "block");
                $(".message.success").text("Your Product Removed from your shopping cart. ");
                setTimeout(function(){
                $('.message.success').hide();
                }, 5000);
                $("#quick-order-summary").load(location.href+" #quick-order-summary>*","");
                require(['jquery','Magento_Customer/js/customer-data'], function ($,customerData) { 
                    var sections = ['cart'];
                        customerData.invalidate(sections);
                        customerData.reload(sections, true);

                });
            }
            else{
                $(".message.error").css("display", "block");
                 $(".message.error").text("Please try again Later.");
                 setTimeout(function(){
                $('.message.error').hide();
                }, 5000);
                $("#quick-order-summary").load(location.href+" #quick-order-summary>*","");

            }

            }
        });
    });
});
</script>
<style>
    body button.action.tocart.primary.green {background-color: #31b41c;color: #fff;border: 1px solid #31b41c;}
    body #quick-order .action.primary:hover {padding: 7px 15px;}
    .product-items {line-height: initial;}
    tr.header-quick-order {background-color: #ececfd;padding: 5px;color: #000;}
    tr.header-quick-order th {font-weight: 500;font-size: 14px;color: #000000;    padding: 21px 5px;}
    .product-item-quick span.product-image-container {width: 60px !important;}
    .product-item-quick a.product-item-link {display: inline;color: #000;font-size: 14px;font-weight:bold;}
    .product-item-quick .product-item-name {display: inline;}
    .product-item-quick .product-item-name {display: block;padding: 0px 0px;    font-weight: 500;}
    .product-item-quick .product-item-details{padding:0px 10px;}
    #quick-order .price-box .price,#quick-order .action_price .price {color: #5bc448;font-family: domine;display:inline-block;padding:0px 0px;font-size: 18px !important;font-weight: 700;}
    #quick-order .price-box.price-final_price {padding: 10px 0px;}
    #quick-order a.action.tocart.primary,#quick-order .stock.unavailable {padding: 14px 20px;border-radius: 0px !important;}
    #quick-order .product-item-actions {margin:0px;}
    tr.body-quick-order td {border-bottom: 1px solid #d7d7d7;}
    body.cms-quick-order .breadcrumbs { display: none;}
    #quick-order .cart-less,#quick-order .cart-more {border: none;background: none;box-shadow:none;font-weight: 600;font-size: 15px;font-family: "poppins";}
    tr.body-quick-order td {font-size: 14px;}
    #quick-order span.price-label{display:none;}
    select#weightoption {max-width: 70%;}
    #quick-order .price-box .old-price .price {color: #888;text-decoration: line-through;}
/*19-10-21*/
@media only screen and (min-width:768px) {
	.quick-order-widget {width: 70%;float: left;}
	.quick-order-summary {float: left;width: 30%;}
	.quick-order-summary {padding: 0px 20px;}
    .quick-order-summary {padding: 0px 15px;}
    .quick-order-widget .block-content {max-width: 95%;margin: 0 auto;}
    tr.body-quick-order td.action_detail {width: 45%;}
    span.product-old-price {font-size:17px;}
    .product-item-quick {display: flex;}
    body button.action.tocart.primary.green {min-width: 106px;}
}
    div#quick-order{width:100%;}
    .cms-quick-order .page-main{max-width:100%;padding-left:0px;padding-right:0px;background-color: #f5f5f6;}
    .quick-order-widget {background-color: #fff;}
    .quick-order-summary  .head-title {font-size: 25px;color: #323433;font-weight: 600;}
    a.quick-checkout {background-color: #fec104;color: #000;text-decoration: none; padding: 10px 20px;width: 100%;display: block;font-weight: 600;text-align: center;max-width: 80%;margin: 0 auto;}
    .quick-cart-item tr td.name {width:52%;}
    .quick-cart-item tr td.qty {width:25%;}
    tr.cart-total td.title {width:72%;font-size: 12px !important;}
    .quick-cart-item tr td.price {width:18%;}
    tr.cart-total td.quick-total {width:28%;}
    .quick-cart-item tr td.name,tr.cart-total td,.quick-cart-item tr td.qty {color: #000;font-weight: 600;font-size: 13px;padding: 11px 10px;}
    .quick-cart-item tr td.price,tr.cart-total td.quick-total {color: #5bc448;font-family: domine;padding: 10px 0px;font-size: 15px !important;font-weight: 700;text-align: left;}
    td.minicart-items {padding: 10px 8px;width: 5%;}
    .quick-cart-total {margin: 10% 0px;}
@media only screen and (max-width:767px) {
    .quick-order-widget .block-content {max-width: 100%;margin: 0 auto;}
    .quick-order-widget .action.primary {padding: 5px;font-size: 13px;}
    /* tr.body-quick-order td {padding: 10px 5px;} */
    tr.body-quick-order td.action_qty{text-align: center;width: 100px;}
    div#quick-order {width: 100%;display: flex;flex-direction: column;}
    #quick-order .quick-order-widget{order:2;}
    #quick-order .quick-order-summary{order:1;padding: 15px 15px;}
    #quick-order .cart-less, #quick-order .cart-more{padding: 7px 5px;}
}
    .product-item-quick .product-image-wrapper{padding-bottom: 100% !important;}
    tr.body-quick-order {width: 100%;}
    span.product-old-price {text-decoration: line-through;color: #8e8e8e !important;font-family: domine;font-weight: 600;}
    button.action.delete.cc_del_btn {box-shadow: none;border: none;background: none;padding:0px 5px;}
    .quick-cart-item tr td.price span, .dis-total{
    color: #727272 !important;
    text-decoration: line-through;
    font-weight: 500;}
    td.dis-total {
    padding: 10px 0px !important;
    font-weight: 500 !important;
}
</style>