<?php
/**
 * Askan Technology
 *
 * @category  AskanTech
 * @package   Askantech_Communication
 * @author    Askan
 * @copyright Copyright (c) AskanTech (https://www.askantech.com/)
 * @license   https://www.askantech.com/Communication/LICENSE.txt
 */
?>
<div>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$customerSession = $objectManager->create('Magento\Customer\Model\Session');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$key_form = $objectManager->get('Magento\Framework\Data\Form\FormKey');

$customerId = '';
if ($customerSession->isLoggedIn()) {
    $customerSession->getCustomerId(); // get Customer Id
    $customerSession->getCustomerGroupId();
    $customerSession->getCustomer();
    $customerSession->getCustomerData();
    $customerId = $customerSession->getCustomerId();
    $customerName = $customerSession->getCustomer()->getName(); // get  Full Name
    $customerEmail = $customerSession->getCustomer()->getEmail(); // get Email
	

	$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
	// echo $product->getId();
	// echo $product->getName();

    ?>
<div id="submit_status"></div>
<div id="submit_status_error"></div>
<form name="enquiry-form" id="enquiry-form" method="post">
<ul class="form-style-1">
    <!-- <li><label>Full Name <span class="required">*</span></label><input type="text" name="field1" class="field-divided" placeholder="First" /> <input type="text" name="field2" class="field-divided" placeholder="Last" /></li> -->
    <li>
    <input name="Productid" id="query_Productid" type="text" value="<?php echo $product->getId(); ?>" hidden />
    <input name="Productname"  id="query_Productname" type="text" value="<?php echo $product->getName(); ?>" hidden />
	<input id="customer_time" name="cus_time" type="text" value="" hidden />
	<input id="frm_key" name="from_key" type="hidden" value="<?php echo $key_form->getFormKey();?>"/>
    <input name="cusid"  id="query_cusid" type="text" value="<?php echo $customerId; ?>" hidden />
        <label>Name <span class="required">*</span></label>
        <input type="text" id="query_contactname" name="contactname" class="field-long" value="<?php echo $customerName; ?>" readonly/>
    </li>
    <li>
        <label>Email <span class="required">*</span></label>
        <input type="text"  id="query_contactemail"  name="contactemail" class="field-long" value="<?php echo $customerEmail; ?>" readonly/>
    </li>
    <li>
        <label>Subject <span class="required">*</span></label>
        <input type="text"  id="query_subject"  name="subject" class="field-long" required/>
    </li>
    <li>
        <label>Your Message <span class="required">*</span></label>
        <textarea name="queries" id="query_message" class="field-long field-textarea" required></textarea>
    </li>
    <li>
        <input type="submit" value="Submit" />
    </li>
</ul>
</form>
<?php }else{ ?>
<div class="not-logged-in">
	<p style="text-align:center;font-size:20px;padding:20px;"><a href="<?php echo $baseurl ?>customer/account/login" >Please Login to Contact Support</p>
</div>
<?php } ?>
<style type="text/css">
.form-style-1 {
	margin:10px auto;
	max-width: 400px;
	padding: 20px 12px 10px 20px;
	font: 13px "Lucida Sans Unicode", "Lucida Grande", sans-serif;
}
.form-style-1 li {
	padding: 0;
	display: block;
	list-style: none;
	margin: 10px 0 0 0;
}
.form-style-1 label{
	margin:0 0 3px 0;
	padding:0px;
	display:block;
	font-weight: bold;
}
.form-style-1 input[type=text],
.form-style-1 input[type=date],
.form-style-1 input[type=datetime],
.form-style-1 input[type=number],
.form-style-1 input[type=search],
.form-style-1 input[type=time],
.form-style-1 input[type=url],
.form-style-1 input[type=email],
.form-style-1 textarea,
.form-style-1 select{
	box-sizing: border-box;
	-webkit-box-sizing: border-box;
	-moz-box-sizing: border-box;
	border:1px solid #BEBEBE;
	padding: 7px;
	margin:0px;
	-webkit-transition: all 0.30s ease-in-out;
	-moz-transition: all 0.30s ease-in-out;
	-ms-transition: all 0.30s ease-in-out;
	-o-transition: all 0.30s ease-in-out;
	outline: none;
}
.form-style-1 input[type=text]:focus,
.form-style-1 input[type=date]:focus,
.form-style-1 input[type=datetime]:focus,
.form-style-1 input[type=number]:focus,
.form-style-1 input[type=search]:focus,
.form-style-1 input[type=time]:focus,
.form-style-1 input[type=url]:focus,
.form-style-1 input[type=email]:focus,
.form-style-1 textarea:focus,
.form-style-1 select:focus{
	-moz-box-shadow: 0 0 8px #88D5E9;
	-webkit-box-shadow: 0 0 8px #88D5E9;
	box-shadow: 0 0 8px #88D5E9;
	border: 1px solid #88D5E9;
}
.form-style-1 .field-divided{
	width: 49%;
}

.form-style-1 .field-long{
	width: 100%;
}
.form-style-1 .field-select{
	width: 100%;
}
.form-style-1 .field-textarea{
	height: 100px;
}
.form-style-1 input[type=submit], .form-style-1 input[type=button]{
	background: #4B99AD;
	padding: 8px 15px 8px 15px;
	border: none;
	color: #fff;
}
.form-style-1 input[type=submit]:hover, .form-style-1 input[type=button]:hover{
	background: #4691A4;
	box-shadow:none;
	-moz-box-shadow:none;
	-webkit-box-shadow:none;
}
.form-style-1 .required{
	color:red;
}

div#submit_status p:before {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 24px;
    line-height: 24px;
    color: #006400;
    content: '\e60e';
    font-family: 'luma-icons';
    vertical-align: middle;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    left: 0;
    text-align: left;
    top: 22px;
    width: 31px;
}
div#submit_status p {
	color: #006400;
    padding: 5px;
    text-align: center;
    /* background: #e5efe5; */
}
div#submit_status_error p {
	color: red;
    padding: 5px;
    text-align: center;
    /* background: #e5efe5; */
}
div#submit_status_error p:before {
	-webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-size: 24px;
    line-height: 24px;
    color: #b30000;
	content:'\e61f';
    font-family: 'luma-icons';
    vertical-align: middle;
    display: inline-block;
    font-weight: normal;
    overflow: hidden;
    speak: none;
    left: 0;
    text-align: left;
    top: 22px;
    width: 31px;
}
</style>
<script>
require(['jquery'],function(){
    jQuery(document).ready(function() {
		$ = jQuery;
        jQuery("#enquiry-form").submit(function(){
			var frm_key=jQuery("#frm_key").val();
            var Productid = jQuery("#query_Productid").val();
            var Productname = jQuery("#query_Productname").val();
			var cusid = jQuery("#query_cusid").val();
			var contactname = jQuery("#query_contactname").val();
			var contactemail = jQuery("#query_contactemail").val();
			var subject = jQuery("#query_subject").val();
			var queries = jQuery("#query_message").val();

            var url = "<?php echo $baseurl.'askantechcommunication/enquiry/index' ?>";
			if (subject != '' && queries != '') {
		    jQuery.ajax({
            url: url,
            type: "POST",
            data: {frm_key:frm_key,Productid:Productid,Productname:Productname,cusid:cusid,contactname:contactname,contactemail:contactemail,subject:subject,queries:queries},
			success : function(result){
			var status = result.status;
				if(status == '1')
				{
					jQuery('#submit_status').html('<p><?= $block->escapeHtmlAttr(__("Thanks for reaching out.")); ?></p>');
					jQuery("div#submit_status_error").empty();
					jQuery("#query_subject").val('');
					jQuery("#query_message").val('');
				}
				else{
					jQuery('#submit_status_error').html('<p><?= $block->escapeHtmlAttr(__("Something went wrong please try later.")); ?></p>');
					jQuery("div#submit_status").empty();
				}
			}
        });
		}else{
			jQuery('#submit_status_error') . html('<p><?= $block->escapeHtmlAttr(__("Please Fill Out Subject and Queries")); ?></p>');
			jQuery("div#submit_status").empty();
		}
		return false;

        });
    });
});
</script>
</div>