 <?php 

 ?>
 <div>
    <a href="#" id="enquiry-form-click">Contact Support</a>
</div>
<div class="enquiry-popup" style="display:none;"><div class="enquiry-content" ><h2 style="text-align:center"><span class="h2" style="font-weight: bold;"> Product Enquiry Form</span><span class="close-enquiry-form">×</span></h2>               
<div id="popup-mpdal" >

   <?php echo $this->getLayout()->createBlock("Askantech\Communication\Block\Form")->setTemplate("Askantech_Communication::form.phtml")->toHtml(); ?>
</div>
</div>
</div>

<script>
require(['jquery'], function () {
    jQuery( "body" ).delegate( "#enquiry-form-click", "click", function() {
        jQuery('.enquiry-popup').show();
        jQuery('body').addClass('chat-enquiry-form-open');
    });
    jQuery( "body" ).delegate( ".close-enquiry-form", "click", function() {
        jQuery('.enquiry-popup').hide();
        jQuery('body').removeClass('chat-enquiry-form-open');
});
});
</script>
<style>
.enquiry-popup {
    position: fixed;
    z-index: 9;
    padding-top: 100px;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    overflow: auto;
    background-color: rgb(0 0 0 / 22%);
}
.enquiry-popup {
    padding-top: 50px !important;
    overflow:hidden;
}
body.chat-enquiry-form-open{
    overflow: hidden;
}
.enquiry-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    width: 50%;
    border-radius: 10px;
}
span.close-enquiry-form {
    float: right;
    font-size: 30px;
    cursor: pointer;
    font-weight: bold;
    margin-top: -13px;
}

@media screen and (max-width: 767px) {
    .enquiry-content {
    width: 90%;
}
.enquiry-popup {
    padding-top: 50% !important;
    overflow:hidden;
}
}
</style>