<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-131039218-1"></script>
<script>
var agent = navigator.userAgent;
        var n = agent.includes("Chrome-Lighthouse");
        if(!n){
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-131039218-1');
}
</script>
<!-- Global site tag (gtag.js) - Google Ads: 985777216 -->
<script>
var agent = navigator.userAgent;
        var n = agent.includes("Chrome-Lighthouse");
        if(!n){
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'AW-985777216');
}
</script>
<!-- Global site tag (gtag.js) - Google Ads: 985777216 -->
<!-- Facebook Pixel Code -->
<script>
var agent = navigator.userAgent;
var n = agent.includes("Chrome-Lighthouse");
if(!n){
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '755906161807152');
fbq('track', 'PageView');
}
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=755906161807152&ev=PageView&noscript=1"
/></noscript>
<!-- End Facebook Pixel Code -->